### ISSUE TITLE
Wierframes for delete a game and show game status

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#1006]
## Description
Currently, there is no way for a user to delete AI:MMO games that have been created. This is an important feature as it will enable users to delete any games which are no longer in use.

They can only be deleted manually by someone on the Code for Life team.

## Acceptance criteria 
- A clear option of deleting existing games
- Prototype or visuals showing flow

**Comment by j4mesholland** [comment]
I have created iterative designs for this solution. They are in the Kurono game landing sketch file.

As the design system is incomplete and development work for the system will be on hold for a few months am showing a solution for the existing portal design style.

**Kurono landing page**
Prototype: https://sketch.cloud/s/9Rqn0/DPWLeQj/play

![AIMMO game page new.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/aed0b6d0-0ecc-46a7-b844-a3f8ce158732)

**Comment by j4mesholland** [comment]
and here is a message on the Classes section of the teacher dashboard: 
__Please note: Kurono preview games will not be shown below, you can view them on the  Kurono game page.__

This should use logic so that it only shows up for preview users of Kurono, as it may be confusing to our Rapid Router users.

![Screenshot 2019-04-04 at 14.17.22.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/176148e8-e0a0-4ad5-a669-f69f0f61d83e)

**Comment by faucomte97** [comment]
This looks good @j4mesholland :)

**Comment by mariaFernando** [comment]
Yep! 👍
