### ISSUE TITLE
Tidy up GameManager

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#1020]
## Description
Currently, the game manager makes heavy use of the kubernetes-client library for tasks such as creating pods and services. However, the approach can be simplified greatly if we were to move the configuration for our kubernetes components into yaml files (or generated a yaml file for dynamic fields such as names).

Here are a couple of examples of how this may be done:
[From the kubernetes-client Python examples](https://github.com/kubernetes-client/python/blob/master/examples/create_deployment.py)
[From the utils module of the Python kubernetes-client](https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py) (similar to the previous example but figures out the resource type from the yaml file)

**Comment by dionizh** [comment]
Not relevant anymore, a lot has changed.
