### ISSUE TITLE
Issues for docker in local mode

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#1022]
## Description
There are a couple of issues surrounding docker in local mode:
* Games are deleted as per #1021, however when using docker the workers are not deleted with the game.
* The `GAME_API_URL` is not pointing towards the django server, but the docker internal DNS url. So when closing stopped games the request is not sent to the Django server as it should be, and games must be closed manually by going to `http://localhost:8000/aimmo/api/games/<ID>/stop/` in order to update the game status.

**Comment by faucomte97** [comment]
@dent50cent is this still an issue?

**Comment by dionizh** [comment]
Fixed by #1525.
