### ISSUE TITLE
Fix the deployment pipelines

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#1067]
## Description
While attempting #1066 I ran into a seemingly unavoidable issue. When installing the Aimmo package (for the frontend) the code does not seem to update correctly (only updates on release/merge to master), to fix this we tried using `pip install --upgrade` to make sure it was getting the latest changes. This, however, causes Aimmo to break (500 error whenever you try to view a game) but doesn't really specify why the error appears (says the `players/game_ide.html` template does not exist). This is making fixing the existing issues such as the game stop mechanic near impossible to fix as we can't test the code we need to run without breaking the code.

**Comment by mrniket** [comment]
We did a quick grooming session for this. With the approach we are going to try, we should be able to avoid some of the issues talked about in the issue.

![IMG_9527](https://user-images.githubusercontent.com/2016308/60604209-1180c480-9daf-11e9-8114-233c6a39802e.jpg)

**Comment by faucomte97** [comment]
Addressed by #1130.
