### ISSUE TITLE
Fix Avatar Twitch

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#1072]
## Description
#1028 adjusts how long it took for us to process turns, they are now a maximum of 2 seconds long. This introduced a glitch on the unity side, as unity updates every 2 seconds and turns can take 1.5 seconds meaning every 3rd update unity games will have a game state 2 turns ahead of the previous one. This leads to the "twitch" meaning everything suddenly jumps to the new location instead of animations playing, this should not happen.

**Comment by mrniket** [comment]
Due to a code review change, this is no longer an issue
