### ISSUE TITLE
Advantage if your avatar goes first

### ISSUE THREAD

**Issue by joshuablake** [ocadotechnology/aimmo#111]
Currently, the order that actions are processed in is determined by the order of the ordering of the dict in avatar_manager (which is arbitrary but consistent for a non-changing dict). Therefore they get first opportunity to get any pickups.

I don't think this is advantageous in any other way as no other actions are specifically processed at the start of every turn except scores (but it doesn't matter when you move onto a score square as they are not exclusive).

Possible resolutions:
- Generate a new pickup whenever one is picked up rather than at the start of a turn cycle.
- Randomise the order each turn so this evens out.
- Randomise when we add pickups each turn.
- Something else?

There is also a possible issue when the ordering changes (which could happen on any write operation to the dict): if two avatars are involved with a fight then one avatar could take two attacks without the other taking any.

**Comment by mikebryant** [comment]
Currently we know the game algorithm isn't scalable (In that more avatars, in combination with turn timeouts, will mean the length of a turn gets longer as we add more players)

Our proposed solution for this is to create a new way of running the game such that all turns happen simultaneously, with a conflict resolution phase afterwards.
We would still like to keep the sequential method for small & tutorial games, as it may be easier to get to grips with.

With that in mind, I'm not sure how much effort we want to put towards making the sequential method fair, as it won't be used in any of the "real" games, as it were..

Randomising turn order would likely be the easiest.

**Comment by joshuablake** [comment]
Superseded by #118.
