### ISSUE TITLE
Printing failing silently

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/aimmo#1116]
**Describe the bug**
Any print statement in Kurono(staging) code is ignored

**To Reproduce**
Steps to reproduce the behaviour:
print("hi") 
print(avatar_state.location)

**Expected behaviour**
Printing

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/c406ed5d-04df-4fc7-b900-48ec3c7d20c5)

**Comment by faucomte97** [comment]
NB: I've just tested this today on staging, and the printing worked fine. Maybe it's something specific to your game rather than a staging-wide issue @rdcruzCFL ?

**Comment by rdcruzCFL** [comment]
I think I had created a new one in the first place but perhaps I didn't. I created a new game and it works fine now. Thanks.
