### ISSUE TITLE
Replace Ingress

### ISSUE THREAD

**Issue by mikebryant** [ocadotechnology/aimmo#113]
We need a local service doing the reverse proxy, and a single ingress just pointing to that service

Because:
* Ingress has a limit on backends
* Reconfiguring the ingress then means it takes a while before it notices the new game

**Comment by mikebryant** [comment]
Note, instead we'd have a static ingress, pointing to our reverse proxy implementation

**Comment by joshuablake** [comment]
The only suitable pre-built solution that I could find is [Ceryx](https://github.com/sourcelair/ceryx).

**Comment by joshuablake** [comment]
Fixed by #147
