### ISSUE TITLE
Kurono rebrand on Kurono pages

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1141]
### Game page
- [ ] Add small logo in top left corner of game page with link to Kurono dashboard page
- [ ] URL: replace `/aimmo/` with `/kurono/` 

### Local dashboard page
- [ ] AI:MMO -> Kurono
- [ ] Replace logo

**Comment by mariaFernando** [comment]
Rapid Router levels are cached, and this doesn't seem to have been an issue for 4 years  I'm not sure if it's still relevant?
