### ISSUE TITLE
Add a local kubernetes implementation

### ISSUE THREAD

**Issue by mikebryant** [ocadotechnology/aimmo#116]
So we can easily test it locally

**Comment by joshuablake** [comment]
Do we want to use Vagrant to make a VM inside which Kubernetes runs (might make it easier to keep track of all the Pods/containers?) or run Kubernetes directly on local machines?

**Comment by mikebryant** [comment]
Preferably vagrant. (Will then make it easy to use on say, windows, rather than us needed to deal with cross platform issues)

**Comment by mikebryant** [comment]
My attempt at this was here: https://github.com/ocadotechnology/aimmo/pull/63
It ended up being very flaky, so not suitable for use right now

**Comment by joshuablake** [comment]
Alternative is [Minikube](http://kubernetes.io/docs/getting-started-guides/minikube/) which appears to be the 'official' solution. Windows support [looks close](https://github.com/kubernetes/minikube/issues/28).

**Comment by mikebryant** [comment]
That looks really cool!
Yeh, I'd be totally up for using that
