### ISSUE TITLE
Permission error on AIMMO games on staging

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/aimmo#1161]
**Describe the bug**
When creating a new game on the test account, access is blocked by CORS policy and the status isn't updated.

**To Reproduce**
1. Log in to staging with the test account
2. Go to Kurono page
3. Create a new game
4. Update the default code
5. See error

**Expected behavior**
The game should run smoothly after booting.

**Screenshots**
![Screenshot 2019-09-03 at 14.31.42.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/db7e1939-5a3b-40b7-b115-abd524e6e737)

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser: Chrome

**Comment by dionizh** [comment]
Seems fixed. We have also tested on staging plenty of times.
