### ISSUE TITLE
[Easy] Screenshots

### ISSUE THREAD

**Issue by servusDei2018** [ocadotechnology/aimmo#1174]
**What is the problem that you wish to solve? Please describe.**
I'd really like to see some screenshots of this game in action.

**Describe the solution you'd like**
I'd like some screenshots, and `readme.md` modified to showcase them.

**Comment by mrniket** [comment]
We are planning to release a landing page in [codeforlife-portal/#1043](https://github.com/ocadotechnology/codeforlife-portal/issues/1043)

Perhaps we can use some of the resources we make for that task here?
