### ISSUE TITLE
Teaching materials for Kurono urls pages

### ISSUE THREAD

**Issue by megamixcraft** [ocadotechnology/aimmo#1184]
**Describe the bug**
Teaching materials for Kurono urls need to be updated. And the text for the links contains "Aimmo" instead of "Kurono". These links need to be updated.

**To Reproduce**
1. Go to 'https://www.codeforlife.education/kurono/'
2. Click on 'Student challenge sheet 1'
3. Takes the user to 'https://www.codeforlife.education/teach/materials/AIMMO_challenge_1'
(Same for Student challenge sheet 2 for Kurono)

**Expected behavior**

The url should be following: 'https://www.codeforlife.education/teach/materials/kurono_challenge_1'

**Screenshots from website**

<p>It looks like now</p><img width="1277" alt="Tech Kurono page 2" src="https://user-images.githubusercontent.com/52087512/66259447-18054a80-e7a9-11e9-951e-93c798005586.png">
<p>Should look like below </p><img width="1234" alt="Update tech Kurono page 2" src="https://user-images.githubusercontent.com/52087512/66259449-19367780-e7a9-11e9-8aad-380fbd4c946d.png">

**Comment by mrniket** [comment]
this has been fixed 😊
