### ISSUE TITLE
Add documentation requirement in new task template

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#1187]
## Task Description

Add `## Documentation Requirements` below the acceptance criteria. This is to make sure we think about what docs to write during task inception.

## Acceptance Criteria

- [ ] there is a documentation requirement/check in new task templates

## Copywrite Requirements

None

## Analytics Requirements

None

**Comment by dionizh** [comment]
Nice idea but task template hasn't been properly utilised.
