### ISSUE TITLE
Add feedback to users on their code

### ISSUE THREAD

**Issue by joshuablake** [ocadotechnology/aimmo#119]
An ability for users to log (maybe just redirecting stdin?) and also to view exceptions in their code. Could also include the events that we associate with each avatar.

Main issue is going to be the security and API to get the information from the worker to the UI. Once workers have authentication (#115) restricting messages to only be view-able by their own player should stop most concerns.

Are we OK with players being able to view other's messages? Otherwise this likely needs to be done via the Django app as that contains the authentication logic.

**Comment by mikebryant** [comment]
Thought:
* The players app generates a secret token per avatar
* This is exposed in the api that the game uses to get the code for each user (and other details like this)
* Then this token can also be pushed to the browser from the players app, and sent directly on the websocket connection to the game

So the game will then know if the user is authorised to view data for that avatar

**Comment by joshuablake** [comment]
The information still needs to end up being shared with Django so that it can be persisted (errors occur when users not logged in, logging/analytics, etc.). How about once per turn (or less often?) the game dumps all the logs (that it collates from all its workers) via the Django API.

If we're doing that anyway then we can probably display to the user via Django as well.

**Comment by mikebryant** [comment]
I would be wary of trying to store the logs in a relational database, especially if users generate a lot. Not really what that sort of database is designed for.
We could store the logs separately in a nosql store of some kind, and mediate access through the django ui app.

**Comment by Spycho** [comment]
Maybe just buffer some in memory - most of the value will usually be from the most recent X log lines.
