### ISSUE TITLE
Add the ability to center on your avatar

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#1191]
### What is the problem that you wish to solve? Please describe.

During one of our testing sessions, one of the most common pain points was how difficult it was to find your avatar when the game loads. On top of that, you have to continuously drag the map to follow your avatar around. Some feedback quotes:

"It would be cool to have a button to centre on our avatar"
"The next usability feature should be to let a player focus on their own avatar so they don't need to search for it in the map"
"How to easily locate the avatar (the small diamond was difficult to find)"
"Should include instructions on how to identify your avatar. Maybe more distinctive marking with some user choice such as clothing colour"

### Describe the solution you'd like
- When the game loads, the game view should be centred and following on your avatar. 
- If you start panning the map, the map should move as expected and the game view stops centring and following your avatar.
- There should be a button on the UI that allows you to centre in on your avatar again.

### Describe alternatives you've considered
We considered having different colours for the avatars to make it easier to signify which one is yours. However, while this partially address the problem (I can easily locate my avatar), it doesn't help you follow your avatar. 

We also considered making the avatar marker more prominent, but this solution has the same disadvantage as the one above

### Additional context
No additional context provided.

**Comment by OlafSzmidt** [comment]
This is done?

**Comment by mariaFernando** [comment]
It's deployed but we're monitoring, so not quite closed yet

**Comment by faucomte97** [comment]
Closing it now as we've monitored it and it's all good :D

**Comment by OlafSzmidt** [comment]
> It's deployed but we're monitoring, so not quite closed yet

Don't monitor in production 😅

**Comment by mariaFernando** [comment]
We QA on staging but keep an eye on production for 24+ hours - here's our shiny [Development Definition of Done](https://drive.google.com/open?id=18IO-YFs_wZYr1zpEQTxQbRjnAMfxYcLC6m8VZ6etmfI)
