### ISSUE TITLE
Camera snaps when uncentering from an avatar mesh on pan

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/aimmo#1197]
**Describe the bug**
When a user drags the map to uncenter the camera from their avatar, there's a snap.

**To Reproduce**
1. Go to https://www.codeforlife.education/kurono/
2. Create a game or enter an already created game
3. Wait for the camera to center on the avatar, then drag on the map

**Expected behavior**
The camera should retain the actual position of the avatar target upon release, so that it transitions seamlessly.

**Desktop:**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 77.0.3865.120

**Additional context**
 This happens because the camera's `centerOn` function uses the avatar's mesh and centers on its bounding box at first. When `unCenter` is called, it clones the mesh's `position` attribute and centers on it. This attribute is, however, set by `createMoveAnimation`, which only sets a keyframe for the initial position and one for the final position, so the result is an integer and offset from the bounding box.

**Comment by mrniket** [comment]
I'm going to close this for now as we haven't got any negative feedback of it in our recent testing. Will reopen if necessary
