### ISSUE TITLE
Map elements change location every time a game starts up

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/aimmo#1215]
**Describe the bug**
Whenever a game is restarted, the code is kept but the obstacles and interactables in the map don't retain their previous positions. This is a continuity problem and might cause UX issues as student challenges progress.

**To Reproduce**
1. Go to https://www.codeforlife.education/kurono/ (logged in)
2. Start a new game
3. Close the game
4. Wait until the game stops then start again
5. See error

**Expected behavior**
Obstacles and interactables should keep their original positions every time a game starts up again.

**Desktop (please complete the following information):**
 - Any

**Comment by mrniket** [comment]
I think this expected behaviour currently is that the obstacles/interactables do move around each time the game is rebooted and therefore this isn't a bug. If we want them to persist, we could revisit this as a feature request. Closing for now
