### ISSUE TITLE
Set up Google Tag Manager

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/aimmo#1255]
## Task Description
As a way to simplify Google Analytics integration in the code, we want to set up a Google Tag Manager container and install it in the project. 

## Acceptance Criteria
- [x] An account is created in Google Tag Manager ( https://tagmanager.google.com/#/home )
- [x] required HTML code is added to the Kurono game page

## Copywrite Requirements
None

## Analytics Requirements
None

**Comment by mrniket** [comment]
Tag not in staging or production, wrong templating language used in handlerbars_template
