### ISSUE TITLE
Set up analytics events with GTM

### ISSUE THREAD

**Issue by MMFernando** [ocadotechnology/aimmo#1256]
## Task Description
Our Google Analytics events are currently coded in via epics. We want to clean this code up and implement them through [Google Tag Manager](https://tagmanager.google.com/#/home) instead.

## Acceptance Criteria
- [ ] Analytics events code has been removed
- [ ] All analytics events are now handled by GTM

## Copywrite Requirements
None

## Analytics Requirements
None

**Comment by mrniket** [comment]
I looked into this and I think this might be a better task to do after the parcel 2 upgrade, deprioritizing for now  until Parcel 2 is out and we have upgraded for it or there is another reason we should switch to putting out google analytic events on GTM

**Comment by faucomte97** [comment]
Closing as we need to revisit the whole GA/GTM approach
