### ISSUE TITLE
Update styled-components

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#1291]
## Task Description
We are getting a few warnings on our project due to an outdated version of styled-components. We should update this library (and anything else that needs to be updated due to this) to remove the warnings

## Acceptance Criteria

- [ ] styled-components library updated to the latest stable version

## Copywrite Requirements

None

## Analytics Requirements

None

**Comment by dionizh** [comment]
styled-component has been updated by @mrniket 9 months ago :)
