### ISSUE TITLE
Avatar marker is disproportionate and in the centre of the map

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1303]
**Describe the bug**
The avatar marker is no longer on top of the player's avatar. It is now stuck on the centre of the map and is about ten times the size.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any of your Kurono games.
2. Observe that the marker is too big and at the centre of the map.

**Expected behaviour**
The marker should go back to being small and on top of the player's avatar.

**Screenshots**
![Selection_018.png](https://images.zenhubusercontent.com/5a0b05968a75884b90875e9b/a55d0c2c-8433-411c-9367-5c82f28e3ce3)

**Comment by mrniket** [comment]
My guess is that the material/object is being initialised but it's not being set to and avatar? or it's some async ordering issues.
