### ISSUE TITLE
New Obstacle Shader

### ISSUE THREAD

**Issue by MMFernando** [ocadotechnology/aimmo#1319]
**Problem**
The current babylon shader for obstacles doesn't have the desired effect in obstacles that aren't cube-shaped. Example (side ridges not visible):
![Screenshot 2020-04-28 at 08.54.32.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/6bd70b5c-ec64-4ca2-9956-2a3ce62d2492)

**Solution**
To be investigated. The shader should either have lines (toon shader) to show details that shadows don't, or have a different light source to bounce off hidden areas.

**Comment by lauracumming** [comment]
@KamilPawel

**Comment by faucomte97** [comment]
Not relevant.
