### ISSUE TITLE
Document the user-facing API

### ISSUE THREAD

**Issue by joshuablake** [ocadotechnology/aimmo#137]
There should be documentation for the API which is used by the Avatar code.

Suggestion: auto-generate with [Sphinx](http://www.sphinx-doc.org/en/stable/).

**Comment by mikebryant** [comment]
+1 on sphinx
As an initial step, we could just host it on readthedocs?

**Comment by CelineBoudier** [comment]
Sphinx is nice indeed!

**Comment by ChrisMukherjee** [comment]
why Sphinx? Why not [Swagger](http://swagger.io), for example?

**Comment by Spycho** [comment]
Because Sphinx is the de facto standard documentation framework for Python, e.g. see the bit of the bottom of https://docs.python.org/3/ that says "Created using Sphinx". It will look more like other python documentation if we use Sphinx.

**Comment by CelineBoudier** [comment]
I think overall we also need to ask ourselves (cc @j4mesholland ): 

- which one will "look" better for teenagers and be more easily integrated in our game

- which one will be better if we extend the available programming languages at some point (NB: we're also thinking about adding some Blockly levels later on after the MLP for the first levels to bridge the gap with Rapid Router for the teenagers that didn't go through the primary curriculum)

- which one will allow us to easily translate the docs later if we localise AIMMO (Sphinx internationalisation also looks more mature than Swagger's http://www.sphinx-doc.org/en/1.5.1/intl.html but I only had a very quick look so far)

**Comment by Spycho** [comment]
I think that misses a point about consistency with other Python docs, which I think is very important, given that we're teaching them Python. Good point about other language support though, if we decide to go that route.

**Comment by CelineBoudier** [comment]
we are working on it - another issue
