### ISSUE TITLE
Refresh needed to load game

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1414]
**Describe the bug**
Reported by @mrniket and reproduced once by @faucomte97 - When loading a game in Kurono, the map view **as well as** the code view is white and the game doesn't load. Refreshing the page fixes the issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load a Kurono game (which can already be started by a teacher)
2. Sometimes, observe that the views are white and the game isn't loading.

**Expected behaviour**
The game should load fine and none of the views should be white.

**Comment by mrniket** [comment]
@faucomte97 is this still an issue? I'm unable to replicate it again

**Comment by faucomte97** [comment]
@mrniket I haven't been able to replicate it either... But it's definitely to Laura and me in the last 2 weeks or so :/

**Comment by faucomte97** [comment]
Might be fixed by Agones - need to test again after it's been deployed.

**Comment by lauracumming** [comment]
I think this is fixed now
