### ISSUE TITLE
Loop in console

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/aimmo#1421]
**What is the problem that you wish to solve? Please describe.**
The console continues to print the error over and over, and it doesn't highlight the line in the code that is incorrect in a syntax error - only an attribute error?

**Describe the solution you'd like**
A pause solution to only print error once, and to highlight where the error is in the code?

**Describe alternatives you've considered**
we haven't yet

**Additional context**
![Screenshot 2020-12-01 at 11.47.07.png](https://images.zenhubusercontent.com/5da58aa016098c0001fb85d1/922aa1ca-3d96-4921-8342-b1a8fcc31223)

**Comment by lauracumming** [comment]
Needs investigation task

**Comment by faucomte97** [comment]
Implemented pause function.
