### ISSUE TITLE
Improve aimmo test coverage

### ISSUE THREAD

**Issue by razvan-pro** [ocadotechnology/aimmo#1425]
## Task Description
After migrating the build/test process to GitHub Actions, test coverage dropped as codecov is now reporting everything. We need to review/exclude the paths we don't want to cover and add more tests where needed.

## Acceptance Criteria
- [ ] Project test coverage >70% (it was ~75% before) - the higher the better of course

**Comment by faucomte97** [comment]
Review this with restructure.
