### ISSUE TITLE
Websockets failing on staging

### ISSUE THREAD

**Issue by joshuablake** [ocadotechnology/aimmo#149]
The websocket request is returning a 400 error (Bad Request). Presumably related to the nginx reverse proxy (#147) but cannot reproduce locally using [this config](https://github.com/joshuablake/aimmo/tree/ingress_minikube).

**Comment by joshuablake** [comment]
#148 was an initial attempt to fix this.

**Comment by joshuablake** [comment]
Anyone know if this was working previously? Looks like it might be [an issue with ingress](https://github.com/kubernetes/kubernetes/issues/24745).

**Comment by mikebryant** [comment]
Websockets have never worked in GCE, to my knowledge

**Comment by OlafSzmidt** [comment]
Working on this right now, solved.
