### ISSUE TITLE
Consider changing GameStateProvider to snapshot rather than lock

### ISSUE THREAD

**Issue by Spycho** [ocadotechnology/aimmo#15]
There are pros and cons in terms of efficiency and functionality

**Comment by danalex97** [comment]
@Spycho Now we use a lock and it seems to take the load for the moment. Is this issue still relevant?

**Comment by Spycho** [comment]
It may well be at scale. We've done no scale testing yet. We're aiming for tens of thousands of users in a single world.

**Comment by OlafSzmidt** [comment]
Relevant.

**Comment by CelineBoudier** [comment]
Relevant I guess

**Comment by OlafSzmidt** [comment]
File is now called a `GameStateProvider`.
