### ISSUE TITLE
Move responsibility for communicating with the workers out of `GameState`

### ISSUE THREAD

**Issue by PhydeauxLeChien** [ocadotechnology/aimmo#155]
Currently the code to get a worker's action is in `AvatarWrapper`, which is 'inside' `AvatarManager` which is 'inside' `GameState`, and the action is then applied to `GameState`, which is a bit odd.

Proposal: move `decide_action` and friends to `DecisionThread`, a helper class that currently has no responsibilities other than to make the `ConcurrentTurnManager` code look cleaner.

Making this task slightly more difficult is the need to rewrite those tests that depend on `DummyAvatar` which supplies actions to tests via an overridden `decide_action`.

**Comment by CelineBoudier** [comment]
Done
