### ISSUE TITLE
Move aimmo-game-creator's game manager into the django codebase

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#1574]
### Discussed in https://github.com/ocadotechnology/aimmo/discussions/1561

<div type='discussions-op-text'>

<sup>Originally posted by **mrniket** July 23, 2021</sup>
Since the django project has access to the kubernetes cluster where the games run, there is no need to manually sync the state of the games in django with the state of the game on the cluster. We could have django as the single source of truth. This could potentially remove a lot of code which would be nice!</div>

**Comment by mrniket** [comment]
@dionizh @razvan-pro Please assign me to this one :)

**Comment by dionizh** [comment]
Assigned :)
