### ISSUE TITLE
Create a funnel / chart for overlap / continuation for Rapid Router and AI:MMO

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#160]

**Comment by CelineBoudier** [comment]
![20161128_170129](https://cloud.githubusercontent.com/assets/8862062/20678046/3129f430-b58d-11e6-8413-bf55a3a4a4bf.jpg)
Draft

**Comment by j4mesholland** [comment]
In Design version in progress

**Comment by j4mesholland** [comment]
[KS chart.pdf](https://github.com/ocadotechnology/aimmo/files/636586/KS.chart.pdf) This has been done.

**Comment by Spycho** [comment]
I think there's something wrong with the Key Stages / ages / years. See https://en.wikipedia.org/wiki/Educational_stage#England_and_Wales.

There are two ages in each year, which makes the chart unclear as to whether the diagram means RR starts at reception or at year one.

KS1 only covers two years (1 and 2).

Do we want to draw KS5 on the diagram for completeness? And either include it in AIMMO's scope, or just have it blank to highlight the gap?

**Comment by CelineBoudier** [comment]
Hm indeed replacing the ages with the Years might work better, @j4mesholland?
We could draw KS5 but here we wanted to focus on the gap between RR and AIMMO @Spycho

**Comment by Spycho** [comment]
Closed, @CelineBoudier? The current chart is incorrect...

**Comment by CelineBoudier** [comment]
It's changed on google Drive...  @j4mesholland would you mind sharing the PDF here?

**Comment by j4mesholland** [comment]
[KS chart.pdf](https://github.com/ocadotechnology/aimmo/files/642781/KS.chart.pdf)

**Comment by Spycho** [comment]
Yes, that looks much better. Cheers!
