### ISSUE TITLE
Find a production name for AI:MMO

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#167]
We can:
Have a brainstorm
Organise a contest with schools / facebook...

We need to think that the name:
- should be easily googlable?
- should reflect the theme and/or learning goals?
- ...

**Comment by CelineBoudier** [comment]
Time Hackers? :)
But i think there are some movies and libs called that already :/

**Comment by mariaFernando** [comment]
Is this closable?

**Comment by CelineBoudier** [comment]
yes... it's...
drumroll....
AI:MMO!
cymbals
