### ISSUE TITLE
Load testing - Kurono changing worksheets

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#1685]
We need to investigate if load might cause an issue on this feature.

Full details here: https://codeforlife.freshdesk.com/a/tickets/439

**Comment by cewei8483** [comment]
Kamil and I had a discussion and figured out how to login with locust:
```
LOGIN_URL = "/login/teacher/"
response = self.client.get(LOGIN_URL)
cookies = response.cookies
csrftoken = response.cookies['csrftoken']
self.client.post(LOGIN_URL,  
    {"auth-username": username, "auth-password": password, "login_view": "", "teacher_login_view-current_step": "auth"},
    headers={'X-CSRFToken': csrftoken},
    cookies=cookies
)
```

**Comment by cewei8483** [comment]
@faucomte97 , most of the time even when I try to manually change the worksheet, it complains 
`WARNING:aimmo.game_manager:Failed to create game, retrying...` (seems to be about agones allocating game servers) and then the change got stuck indefinitely.

**Comment by SKairinos** [comment]
Taking aimmo offline
