### ISSUE TITLE
User Research: create feedback forms for teachers

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#169]

**Comment by CelineBoudier** [comment]
@j4mesholland Is it still relevant? :)

**Comment by j4mesholland** [comment]
It will be but later in the process (when we have mockups and rough teaching materials)

**Comment by OlafSzmidt** [comment]
@j4mesholland I'll move it to New Issues instead then. Maybe we can create some dependencies for this issue (the mockups, etc)
