### ISSUE TITLE
Backpack Attribute Erro

### ISSUE THREAD

**Issue by WhineyMonkey10** [ocadotechnology/aimmo#1726]
**Describe the bug**
When trying to use the backpack, the module doesn't exist on avatar_state (AttributeError: 'AvatarState' object has no attribute 'backpack')
**To Reproduce**
1. Go to kurono
2. Try to access your backpack
3. Execute Code

**Expected behavior**
Backpack being a module of avatar_state, allowing me to access it's information.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
Doing this for a school project, quite easy, but good idea!

**Comment by faucomte97** [comment]
@faucomte97 Check if it's still relevant

**Comment by SKairinos** [comment]
Taking aimmo offline
