### ISSUE TITLE
Delay in Kurono

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/aimmo#1755]
Fix the delay in Kurono. 
Messages appear before the avatar has actioned the corresponding movement. 
The logs appear beforehand.

Investigation task: https://app.zenhub.com/workspaces/code-for-life-admin-5cf7f1b750c6a6242c50af4c/issues/gh/ocadotechnology/codeforlife-admin/813

**Comment by cewei8483** [comment]
The real turnCount increment happens in `GameRunner` class, which is in BE.
All the increments in FE only affect the log shown in the bottom left of the screen, and I guess their purpose are to make turnCount start from 1. (It starts from 0 in BE, so basically it's about indexing)

**Comment by SKairinos** [comment]
Taking aimmo offline
