### ISSUE TITLE
Document outlining the research that we have done so far via student questionnaires

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#176]
- Introduction
- PEGI ratings
- Most popular games (from our questionnaires)
- Most popular games below PEGI age 18 rating (From the retailer, Game)
- Games of special note
- Similar coding games for teens
- Comments about our game concepts for AI:MMO

**Comment by OlafSzmidt** [comment]
@j4mesholland ?

**Comment by j4mesholland** [comment]
Teenager game preferences: https://docs.google.com/spreadsheets/d/1gE3ZklFi12EOtXLSNvwyajDP-zHkzcuv-oO0OMYP7Lo/edit#gid=0

Game popularity count: https://docs.google.com/spreadsheets/d/1lQLnXInkF2kjsZjgOcHgSMJh3aMrduttyvzLYclfATc/edit#gid=0

Coding games:
https://docs.google.com/spreadsheets/d/1RwL-bv6S-uGNKeBR3E-RHSSHOxloVujRPKaEXO9TGiA/edit#gid=0

Game concept student feedback:https://docs.google.com/forms/d/1wu_LTQkhGm6rIaoRhWAghDhx5Pzkq1OtwZFQgBciJtI/edit#responses
