### ISSUE TITLE
The map can't be seen on aimmo/watch/

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#185]
Console log:
`socket.io.min.js:2 GET http://staging.aimmo.codeforlife.education/game/main/socket.io/?EIO=3&transport=polling&t=LhtI7E3 
i.create @ socket.io.min.js:2
i @ socket.io.min.js:2
o.request @ socket.io.min.js:2
o.doPoll @ socket.io.min.js:2
n.poll @ socket.io.min.js:2
n.doOpen @ socket.io.min.js:2
n.open @ socket.io.min.js:2
n.open @ socket.io.min.js:2
n @ socket.io.min.js:2
n @ socket.io.min.js:1
n.open.n.connect @ socket.io.min.js:1
(anonymous) @ socket.io.min.js:1
(index):1 XMLHttpRequest cannot load http://staging.aimmo.codeforlife.education/game/main/socket.io/?EIO=3&transport=polling&t=LhtI7E3. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://staging-dot-decent-digit-629.appspot.com' is therefore not allowed access. The response had HTTP status code 502.
socket.io.min.js:2 Mixed Content: The page at 'https://staging-dot-decent-digit-629.appspot.com/aimmo/watch/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://staging.aimmo.codeforlife.education/game/main/socket.io/?EIO=3&transport=polling&t=LhtI8SW'. This content should also be served over HTTPS.`

**Comment by mikebryant** [comment]
Duplicate of #114?

**Comment by CelineBoudier** [comment]
Activating the loading of unsafe scripts doesn't work anymore...

**Comment by adstastic** [comment]
¯\_(ツ)_/¯

**Comment by OlafSzmidt** [comment]
Done!!!! :)
