### ISSUE TITLE
Choose a game theme

### ISSUE THREAD

**Issue by Spycho** [ocadotechnology/aimmo#2]
Choice might depend on #1.

Candidates include:
- Space / Sci-Fi
- Fantasy
- Something "Ocado"
  - Supply chain
  - Vehicle routing
  - Warehousing
- Any many more...

**Comment by yongjizhou** [comment]
Something "Ocado" ->Warehouse -> OSP Rainbow grid and bots

**Comment by j4mesholland** [comment]
We have decided on a Time Travel game to appeal to a broad audience of students.

**Comment by OlafSzmidt** [comment]
@CelineBoudier Is this done?

**Comment by CelineBoudier** [comment]
@OlafSzmidt Yes, but it has become an epic for everything related to stories and names - I'll remove the epic and close as it doesn't make a lot of sense
