### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by danalex97** [ocadotechnology/aimmo#207]
We need some integration testing. My idea was to create a mock django server that would capture all request and responses and potentially deploy the server to an actual cluster. The idea seems to work locally with threads and minikube(not finished yet) -- you can see the work on branch "tests".

**Comment by OlafSzmidt** [comment]
As discussed with Dips @dips7189. We probably want:

A global game worker and game creator. 
Reset each one from test to test.
We need to maintain a map unless one of the above creates one. And feed them in.
