### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#225]
The file *setup.py* has no python version requirement. For some reason my virtualenv is running python3 and not 2.7 like everyone else. I'm on arch linux. Running the *./run.py* returns back this:

> Traceback (most recent call last):
>   File "/home/olaf/Documents/Ocado/aimmo/example_project/manage.py", line 13, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/core/management/__init__.py", line 328, in execute
>     django.setup()
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
>     app_config.import_models(all_models)
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
>   File "/home/olaf/Documents/Ocado/aimmo/players/models.py", line 11, in <module>
>     ] + [('Level%s' % i, 'Level %s' % i) for i in xrange(1, app_settings.MAX_LEVEL+1)]
> NameError: name 'xrange' is not defined
> Traceback (most recent call last):
>   File "./run.py", line 31, in run_command
>     subprocess.check_call(args)
>   File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['python', '/home/olaf/Documents/Ocado/aimmo/example_project/manage.py', 'migrate', '--noinput']' returned non-zero exit status 1.
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./run.py", line 87, in <module>
>     main('--kube' in sys.argv or '-k' in sys.argv)
>   File "./run.py", line 58, in main
>     run_command(['python', _MANAGE_PY, 'migrate', '--noinput'])
>   File "./run.py", line 33, in run_command
>     log('Command failed with exit status %d: %s' % (e.returncode, ' '.join(args)))
>   File "./run.py", line 23, in log
>     print >> sys.stderr, message
> TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
> Terminated

On the other hand *python2 run.py* returns this:

> Traceback (most recent call last):
>   File "/home/olaf/Documents/Ocado/aimmo/example_project/manage.py", line 13, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/core/management/__init__.py", line 328, in execute
>     django.setup()
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
>     app_config.import_models(all_models)
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/home/olaf/.virtualenvs/aimmo/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
>   File "/home/olaf/Documents/Ocado/aimmo/players/models.py", line 11, in <module>
>     ] + [('Level%s' % i, 'Level %s' % i) for i in xrange(1, app_settings.MAX_LEVEL+1)]
> NameError: name 'xrange' is not defined
> Command failed with exit status 1: python /home/olaf/Documents/Ocado/aimmo/example_project/manage.py migrate --noinput
> Traceback (most recent call last):
>   File "run.py", line 87, in <module>
>     main('--kube' in sys.argv or '-k' in sys.argv)
>   File "run.py", line 58, in main
>     run_command(['python', _MANAGE_PY, 'migrate', '--noinput'])
>   File "run.py", line 31, in run_command
>     subprocess.check_call(args)
>   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command '['python', '/home/olaf/Documents/Ocado/aimmo/example_project/manage.py', 'migrate', '--noinput']' returned non-zero exit status 1
> Terminated

**Comment by danalex97** [comment]
I think this is a versioning problem. Afaik Python 2.7 can upgrade to Python 3.6, but not the reverse. Imho, we should try to move the whole project in 3.6.
