### ISSUE TITLE
Game action refactoring

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#228]
So @danalex97 and I came across _action.py_ and noticed there's room for improvement (?). The constructor for the Action class tries to add `self.direction` to an attribute from avatar.

`self.direction` is initialized in the child class, WaitAction. That constructor calls `super().__init__`. Don't think it's great practice and maybe we should consider refactoring this.

**Comment by CelineBoudier** [comment]
Still relevant
