### ISSUE TITLE
Add CodeClimate

### ISSUE THREAD

**Issue by danalex97** [ocadotechnology/aimmo#229]
Maybe we should add codeclimate as we are not consistent with the style everywhere.

**Comment by CelineBoudier** [comment]
Yes I suggested it on @OlafSzmidt pull request :)

**Comment by danalex97** [comment]
I know, I just thought we should add an issue to not forget about it.

**Comment by CelineBoudier** [comment]
:+1:  Yes we should ^^ Thanks for adding this issue @danalex97

**Comment by dionisioC** [comment]
Hi, this issuee is about add codeclimate, or refactor the codebase to be more pep8 compilant?

**Comment by OlafSzmidt** [comment]
Hi @dionisioC - the issue is about adding codeclimate so that our code is more pep8 compliant.

**Comment by OlafSzmidt** [comment]
Changed the title and description so we don't confuse anyone else ;)

**Comment by dionisioC** [comment]
Thanks, I forked the repo, I want to try to add codeclimate

**Comment by OlafSzmidt** [comment]
@dionisioC Good luck!

**Comment by CelineBoudier** [comment]
Relevant

**Comment by CelineBoudier** [comment]
Added the dashboard
