### ISSUE TITLE
Unique game page

### ISSUE THREAD

**Issue by ramonfmir** [ocadotechnology/aimmo#234]
Right now each game has two pages: the 'program' page and the 'watch' page. We would like to merge both to make it look more like @j4mesholland's mockups.

![console-ui-victorian](https://user-images.githubusercontent.com/3001940/30104302-20fd2c10-92ed-11e7-9ae1-7cc8ba755094.jpg)

Some work towards accomplishing that has been done by @danalex97 in the [views](https://github.com/ocadotechnology/aimmo/tree/views) branch.

**Comment by CelineBoudier** [comment]
Is it still needed?

**Comment by danalex97** [comment]
Either this or find a way to load Unity faster. It takes ~6 seconds to load a level as opposed to one load if we make a unique game page. Besides this, I don't think is needed.

**Comment by j4mesholland** [comment]
This has been replaced with the following UI:
![nav spilt mmo](https://user-images.githubusercontent.com/18662916/35563538-e53b8df4-05ae-11e8-8ce9-5277350bb287.png)
