### ISSUE TITLE
Some migrations are not made

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#236]
I'm on the unity branch.
When running the project, it asked me to make migrations as the models have changed.
Migrations should be created by the developer changing the models.py file.
Because the migrations are then applied to our database in production :)

**Comment by OlafSzmidt** [comment]
@danalex97 @ramonfmir ????

**Comment by OlafSzmidt** [comment]
@CelineBoudier was running the `run` file instead of the `run.py` file. We should remove the file from the repo?

**Comment by OlafSzmidt** [comment]
Pretty sure this is now closed.
