### ISSUE TITLE
Minimum Product: Refactor world_map

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#243]
Found a 

> TODO: refactor into GameState (this class does too much) 

comment inside the `world_map.py` file and I completely agree. 

We should move the logic and the file elsewhere.

**Comment by ramonfmir** [comment]
In the unity branch we created something called world_state since the word 'game' has a specific meaning in AI:MMOs design. I don't know how outdated that code is but that might give you some ideas.

**Comment by OlafSzmidt** [comment]
Change of plans. This is now part of our **_[MLP](https://github.com/ocadotechnology/aimmo/milestone/1)_** milestone. Most likely the whole file will move to a separate package within the game (called `maps` as we speak), and some of the logic will move to a package called `state`.

**Comment by OlafSzmidt** [comment]
Relevant!

**Comment by CelineBoudier** [comment]
@mrniket ;)
