### ISSUE TITLE
Minimum Product: managers package

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#257]
In reality, we don't really need the turn manager or worker manager for our levels game however I think it would be too difficult to get rid of them just for the purpose of the minimum product (provided many tests are based on this too, which we don't want to change or remove just yet).

Thus, `managers` package! :)

**Comment by danalex97** [comment]
They would also allow zombies in levels, which could be quite cool.

**Comment by OlafSzmidt** [comment]
`turn_manager` is not an issue as it was already moved on the `managers_package` branch, but I can't move `worker_manager` without getting 500 codes.

**Comment by danalex97** [comment]
@OlafSzmidt  The test case was actually correct as the game was not working locally. I was able to do move the file. I'll make a pull request. 

The problem was with the paths as I was getting the same 500 error.  
```python
worker_directory = os.path.join(
        os.path.dirname(__file__),
        '../../../aimmo-game-worker/',
    )
```
Do you think we should make all paths absolute?

**Comment by OlafSzmidt** [comment]
@danalex97 - Yes. Not only it's a PEP8 convention to use absolute paths but also it makes the code more readable in my opinion. We share names a lot in this codebase for files so it's easy to make a mistake.

**Comment by danalex97** [comment]
We should keep the same convention everywhere I guess. We can't have fully absolute paths for now cause #235

**Comment by CelineBoudier** [comment]
(Managers is actually a name which can be misleading as it doesn't really explain what it's supposed to do, a step for later might be to think about refactoring this more deeply?)

**Comment by OlafSzmidt** [comment]
@CelineBoudier - we can do this sooner than later perhaps as we have a unmerged PR right now? What name do you suggest?

**Comment by CelineBoudier** [comment]
@OlafSzmidt I'm answering on the PR

**Comment by OlafSzmidt** [comment]
#282 is now the relevant issue.
