### ISSUE TITLE
Minimum Product: generates_score from cell

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#262]
I can't remove the uses of `generates_score` right now without getting a 500 status code in the integration tests at the end. If someone has a solution for this, that would be great.

It includes removing `generates_score` from `cell.py` and especially the serialized output of the class. That's used further in `game_state` and `test_world_map`, but there are other instances where generates_score occurs too.

**Comment by danalex97** [comment]
It may be useful to run the tests verbosely. To do that, you  can change:

```pyhton
self._VERBOSE = False
```

on line 49 in `test_end_to_end`

**Comment by danalex97** [comment]
Which branch?

**Comment by OlafSzmidt** [comment]
They're all outdated by now. But you will find my initial attempt in the last commit of 

`OlafSzmidt:cell_refactoring'

**Comment by danalex97** [comment]
Are you sure is [this](https://github.com/OlafSzmidt/aimmo/tree/cell_refactoring)? Btw, are we going to remove all these in aimmo-unity as well?

**Comment by OlafSzmidt** [comment]
So idea is to get everything removed to a point where we have only the code required to create our Level1 and move upwards from that. 

That being said; we don't remove things that will be too complicated to remove. One of them being our turn and worker managers. I'm still not sure how this will work but we will figure it out.

And sorry, I didn't push that old commit I was speaking of - it's on that branch now.

**Comment by danalex97** [comment]
The test  in `aimmo-game` fail cause you removed this:
```python 
             [
                 {'pickup': MockPickup('b'), 'avatar': avatar_manager.avatars_by_id[1]},
                 {},
                 {'generates_score': True},
           ],
```

A quickfix would be to replace `{'generates_score': True}` with `{}`.

**Comment by danalex97** [comment]
I also get this stacktrace afterwards:
```
FAIL: test_local_level_1 (test_end_to_end.TestService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ad5915/aimmo/integration-tests/tests/test_end_to_end.py", line 226, in test_local_level_1
    def test_local_level_1(self): self.level_1(kube=False)
  File "/home/ad5915/aimmo/integration-tests/tests/test_end_to_end.py", line 158, in level_1
    'password':'admin'})
  File "/home/ad5915/aimmo/integration-tests/tests/test_end_to_end.py", line 96, in __post_resource
    self.assertEqual(result.status_code, code)
AssertionError: 500 != 200
```
So the service crashes when someone loges in. This is just because of some wrong imports, that I believe you already solved now:
```
  File "/tmp/tmppcKVI8/avatar.py", line 4, in handle_turn
    from simulation.geography.direction import ALL_DIRECTIONS
ImportError: No module named geography.direction
```

**Comment by OlafSzmidt** [comment]
Many thanks Alex. I'll look into it :) Don't know if replacing a dictionary with an empty dictionary will be ok for the rest of the code elsewhere though. That's the problem with making changes like these, there's always something depending on it.

**Comment by danalex97** [comment]
That was code inside a test, though, so it shouldn't do harm.

**Comment by OlafSzmidt** [comment]
Ah, yesss. Thanks!:)
