### ISSUE TITLE
Game Worker/ test_world_map: Multiple tests incorrect

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#273]
Came across multiple tests inside `aimmo-game-worker/tests/simulation/test_world_map.py` that use the method `is_visible` that is being called to an instance of `WorldMap`. 

This method was never implemented (I checked history on github), so not sure what the intention was here. Perhaps `is_on_map()`, to investigate.

**Comment by OlafSzmidt** [comment]
So what happened here is that my intellij is confused and thinks the code imports `WorldMap` from `aimmo-game`. What actually is imported by the line:

`from simulation.world_map import WorldMap`? IntelliJ tells me it's aimmo-game, but I find that hard to believe.

**Comment by danalex97** [comment]
Looking at `setup.py` and the test, I think is just Intellij :thinking:

**Comment by OlafSzmidt** [comment]
@CelineBoudier Can you try on your IDE?
