### ISSUE TITLE
Buggy constructor for MockCell in tests!

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#274]
The `MockCell` constructor contains a parameter `actions` that has a default mutable argument. 

This has potential for bugs. If I understand correctly, a new list will not be created with each call that has no actions parameter specified. [Python's defaults arguments are evaluated once when the function is defined, not each time the function is called](http://docs.python-guide.org/en/latest/writing/gotchas/). 

Therefore later down the code when we actually mutate the actions list (which we believe is 'fresh'), we risk changing a list that was created for a previous `MockCell` instead. 

This only works correctly if we are only making one (or none) call to `MockCell` with `action` not specified.

**Comment by danalex97** [comment]
Is this the case in the constructor? Just out of curiosity, how would the code look like?

**Comment by danalex97** [comment]
Sorry, I read more about this. Very cool bug. Good job @OlafSzmidt  :tada:
