### ISSUE TITLE
Teenagers want to feel comfortable with basic Python syntax / typing

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#279]
so they can learn with the game

**Comment by CelineBoudier** [comment]
@j4mesholland please review the "goal oriented" epics:
- remove doubles
- prioritise them
- add relevant issues there with help of team / planning
Thanks ^^

**Comment by CelineBoudier** [comment]
This is like a big epic - @j4mesholland ?

**Comment by j4mesholland** [comment]
Not stale

**Comment by OlafSzmidt** [comment]
Relevant.

**Comment by j4mesholland** [comment]
not stale
