### ISSUE TITLE
Flat World Movie 

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/aimmo#286]
Character walks from the van to the object to be picked, picks it up and walks back.

**Comment by CelineBoudier** [comment]
Do we have the mockup for the "wait 1 turn" so we can test the king of the hill? cc @j4mesholland @OlafSzmidt

**Comment by mariaFernando** [comment]
No, but I can work on it. How would it translate, visually? (Is it the character standing still or spinning?)

**Comment by CelineBoudier** [comment]
I don't know visually, but there should be a notification with number of turns. I don't remember how it looks like now in the API, but the idea would just be to have something making it clear that you're staying for a "turn" in the  delivery  location. Adding @Spycho to the loop :)
