### ISSUE TITLE
Prototype website - Rapid Router van and road movie

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#291]
Record movement of RR van moving along a road and save as .Mov file.

**Comment by mariaFernando** [comment]
Is the movie supposed to end on the road? Just saying this because the very first "comic" slide begins with the van stopped in front of a house.

**Comment by j4mesholland** [comment]
Updated video now stops at the house the correct way around. We might need to tinker with it so the red destination box disappears.

**Comment by OlafSzmidt** [comment]
@j4mesholland Any updates on this tinkering?
