### ISSUE TITLE
Data untrusted on init of Action

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#319]
Right now, the data we pass to either `AttackAction` or `MoveAction` cannot be trusted. More specifically it is the `direction` parameter. There is no checking done anywhere to see whether this has potential to break the game or not. 

`is_legal()` doesn't do enough, imo.

**Comment by OlafSzmidt** [comment]
Still relevant.

**Comment by OlafSzmidt** [comment]
As above

**Comment by j4mesholland** [comment]
not stale

**Comment by OlafSzmidt** [comment]
Needs investigating. This might have been fixed with recent changes though.

**Comment by NiallEgan** [comment]
Imo this can be closed. As it currently stands, the path of user controlled data is as follows:
- User returns an object from their handle turn method, say `action`
- The worker pod then calls `action.serialise()`. This returns a dict representation of valid actions (or objects with a `serialise` method).
- This dict then gets sent back to the game pod.
- In the game pod, we then look up the appropriate action using the dict. We also pass args that are extracted from the dict. At this point, if the action is invalid, or the arguments that are passed to it are not correct, we will get an exception (which we subsequently catch). Thus the user cannot actually control the game pod beyond choosing from specific predefined actions and arguments.
