### ISSUE TITLE
Moving the die logic of an avatar

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#355]
I found this while writing tests in `action.py` in method `_apply()` of class `AttackAction`. This is most definitely not the place where we want to have this logic and should move it sooner than later.

![Code](https://i.imgur.com/36jYNKH.png)

**Comment by danalex97** [comment]
I think die is only used here. We could make die take only the world map as an argument. Would this work?

**Comment by OlafSzmidt** [comment]
So moving the `die()` function to `AvatarWrapper` and passing `world_map` to it? How do we decide where the user respawns?

**Comment by danalex97** [comment]
From what I see currently we do random. I think this is fine for now, right?

**Comment by OlafSzmidt** [comment]
Still relevant, but we need to discuss how exactly this will be used.

**Comment by OlafSzmidt** [comment]
As above
