### ISSUE TITLE
Obstacles: width, height, type, orientation

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#357]
The serialisation we're currently implementing with @mrniket passes a JSON with the following fields:

`width`, `height`, `type`, `orientation`. 

- [ ] We need to add more obstacle logic (such doesn't exist right now, we assume any cell that has `False` as its `habitable` value is an obstacle, no getters etc all). 
- [ ] Introduce the concept of `width` and `height` to obstacles.
- [ ] Obstacles should have different `type`s. For example, it could be a wall.
- [ ] We need `orientation` for rendering purposes.

**Comment by OlafSzmidt** [comment]
Relevant. Unsure about the `orientation` point. More discussion maybe in #360

**Comment by j4mesholland** [comment]
not stale

**Comment by j4mesholland** [comment]
not stale

**Comment by CelineBoudier** [comment]
is it still relevant?

**Comment by mrniket** [comment]
Still relevant
