### ISSUE TITLE
World "era" state

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#358]
Once again, during serialization, we realized we need to add an `era` element to our JSON in order to decide what assets will be used in the back end. 

This element will be passed on the highest level from `service.py`, probably somewhat close to what you can see below in the screen-shot. We need this functionality.

**Comment by OlafSzmidt** [comment]
Not stale.

**Comment by j4mesholland** [comment]
@mrniket @OlafSzmidt Is this still an issue?

**Comment by CelineBoudier** [comment]
still relevant if we think about our recent discussions

**Comment by mrniket** [comment]
Still relevant
