### ISSUE TITLE
Delta's for serialisation updates

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#359]
As we have reverted @danalex97 's and @ramonfmir's implementation of delta's, we definitely need to introduce them again to have a better performing game in the future. 

We could consider cherry picking some commits, but improvements should be done too as it needs to reflect the current code.

**Comment by OlafSzmidt** [comment]
Still relevant.

**Comment by CelineBoudier** [comment]
yup

**Comment by j4mesholland** [comment]
not stale
