### ISSUE TITLE
Orientation of an avatar

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#360]
For JSON, we need to pass `orientation` of an avatar. This could be just one of the cardinal directions I presume, not specific bearings or anything (not 100% on this, down to discuss). 

Might be worth looking at `is_towards()` when you implement this.

**Comment by OlafSzmidt** [comment]
Right now the orientation is calculated on the front-end I believe based on previous locations for the animation. We need to consider situations where the connection will be corrupted and one turn will not be received though, etc.

@mrniket @mariaFernando

**Comment by mariaFernando** [comment]
The orientation is calculated on the front-end based on previous locations? Is it not received from the backend DTO?

**Comment by CelineBoudier** [comment]
Looks stale to me? @OlafSzmidt @mariaFernando

**Comment by OlafSzmidt** [comment]
Done.
