### ISSUE TITLE
Investigate Serialised Cells & Location

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#366]
So the JSON we wanted for the back-end seems to be finished in the PR's now, but there's still a serialise method in the cell that may be redundant?

Investigation needed as to what we need to do with this.

![code](https://i.imgur.com/FUkh1eH.png)

Same applies to **location**. There's a serialise method in there.

**Comment by OlafSzmidt** [comment]
Still relevant. `service.py` does not use this for sending updates anymore.

**Comment by CelineBoudier** [comment]
@OlafSzmidt
