### ISSUE TITLE
Create 3D Prehistory Trees

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/aimmo#375]
Current progress:
![Screen Shot 2017-11-27 at 12.35.52.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/457969f2-2baa-4bb5-9332-446c63ef5e44)

**Comment by mariaFernando** [comment]
@CelineBoudier @j4mesholland @OlafSzmidt @mrniket any thought?

**Comment by mrniket** [comment]
Trees look good and low poly :) How do they look like in different lighting conditions?

**Comment by mariaFernando** [comment]
[Uploading... Screen Shot 2017-11-28 at 09.43.50.png ]
