### ISSUE TITLE
Create 3D Prehistory Brachisaurus

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/aimmo#387]
![Screen Shot 2017-11-29 at 11.00.44.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/e4a131fd-15bc-45e8-be6e-1a6ca377c893)![Screen Shot 2017-11-29 at 11.00.36.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/34a097ad-b836-4b2a-b9a0-b25bf90c1fac)

**Comment by mariaFernando** [comment]
![Screen Shot 2017-11-29 at 11.00.44.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/857d22d9-52a3-46b3-8efd-c9c9946e2699)

@CelineBoudier @mrniket @OlafSzmidt @j4mesholland

**Comment by j4mesholland** [comment]
This looks great!

**Comment by CelineBoudier** [comment]
:heart_eyes:

**Comment by OlafSzmidt** [comment]
wicked x2

**Comment by mrniket** [comment]
@mariaFernando what's the size of this?

**Comment by mariaFernando** [comment]
@mrniket I've got 4.978 x 9.686 x 15.1, which I guess would be rounded to 5 and 10 squares?
