### ISSUE TITLE
Create 3D Triceratops

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/aimmo#388]
![Screen Shot 2017-11-29 at 11.00.44.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/5c192342-2315-4865-80fb-c8dc7de3b433)

**Comment by CelineBoudier** [comment]
:heart_eyes:

**Comment by OlafSzmidt** [comment]
looks wicked

**Comment by mrniket** [comment]
What's the size of this? (for the backend)
