### ISSUE TITLE
MMO UI Tricy Nav Video

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#389]
- [x] Create mockup in UI design
- [x] Write MMO Goals
- [x] Decide on code hints and answers
- [x] Make video prototype

**Comment by j4mesholland** [comment]
Please review:
![nav spilt mmo goals](https://user-images.githubusercontent.com/18662916/33377776-8ec2cc46-d50a-11e7-9a4f-46948bfb96cb.png)
![nav spilt mmo](https://user-images.githubusercontent.com/18662916/33377779-92b2f47a-d50a-11e7-9e7f-d3003fc55afe.png)

**Comment by mrniket** [comment]
"the green guilding" should be "the green building"

**Comment by OlafSzmidt** [comment]
"walking" not "waking" in third paragraph. 

How does the blue box work on the second screenshot? There's an exit button, what happens then?

**Comment by j4mesholland** [comment]
@OlafSzmidt it says 'walking' already. Once the code hints are gone the ACE editor expands to that space.
@mrniket I have fixed to say 'building' now.

**Comment by j4mesholland** [comment]
![nav spilt mmo goals](https://user-images.githubusercontent.com/18662916/33378300-49da1038-d50c-11e7-99d0-dac394926953.png)

**Comment by j4mesholland** [comment]
![nav spilt mmo goals](https://user-images.githubusercontent.com/18662916/33378365-765b813c-d50c-11e7-81ba-e3a1973b7e2f.png)

**Comment by CelineBoudier** [comment]
"Now you will help to program your avatar" => sounds a bit strange to me?

**Comment by j4mesholland** [comment]
How about 'Now you will program...'

**Comment by j4mesholland** [comment]
Please test the video: https://drive.google.com/open?id=12m9uNzWAMC3zJsgi300SIFiuX5L9l7JV

**Comment by OlafSzmidt** [comment]
Not sure what the video is supposed to be for, but I would crop it. Ends abruptly too. Typing / selecting could be better too.
