### ISSUE TITLE
Teaching Materials for MMO

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#427]
- explain different strategies: pickup seeker, warrior, random (and why it doesn't work well), score seeker.... 
- API description: what they can use to implement different strategies
- explain more in detail example codes (random, ..)?

**Comment by CelineBoudier** [comment]
This is also a big epic - unless it has some doubles anywhere else @j4mesholland ?

**Comment by j4mesholland** [comment]
Just need to finalise the user guide

**Comment by j4mesholland** [comment]
All teaching materials for MVP finished.
