### ISSUE TITLE
Fix broken and skipped Kubernetes tests 

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#432]
As we stand, there are two basic tests that need to be written in `test_kubernetes` as well as one needs to be fixed. All three are skipped by a unittest decorator.

**Comment by CelineBoudier** [comment]
Loving the spelling ;)

**Comment by OlafSzmidt** [comment]
Still not done. Good starter task.

**Comment by j4mesholland** [comment]
not stale

**Comment by mrniket** [comment]
Still relevant
