### ISSUE TITLE
I want to understand the turn based system of AIMMO

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#437]
So that I can explain to my class

**Comment by j4mesholland** [comment]
[KS3-HandleTurn.pdf](https://github.com/ocadotechnology/aimmo/files/1674552/KS3-HandleTurn.pdf)
Please review

**Comment by j4mesholland** [comment]
[KS3-HandleTurn_V2.pdf](https://github.com/ocadotechnology/aimmo/files/1707555/KS3-HandleTurn_V2.pdf)
Updated file for review
