### ISSUE TITLE
Are the concepts we teach understandable by teenagers, and is the concept appealing enough

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#440]
Prep questionnaire for A. and S. schools class user tests

**Comment by j4mesholland** [comment]
Results from ASL: https://docs.google.com/forms/d/1wYO5Kyq362Dq1Lzcaa7G8-554-ZLROJKIQsh1C_78fM/edit

**Comment by mrniket** [comment]
Looks good to me! :)

**Comment by j4mesholland** [comment]
See responses here: https://docs.google.com/forms/d/1wYO5Kyq362Dq1Lzcaa7G8-554-ZLROJKIQsh1C_78fM/edit#responses

**Comment by j4mesholland** [comment]
The majority liked AI:MMO
