### ISSUE TITLE
Make sure teachers are comfortable with the overall logic of programming AI:MMO

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#472]
- [x] turn based system
- [ ] scores
- [x] pickups
- [x] Avatar
- [x] API
...

**Comment by j4mesholland** [comment]
Not stale - will be part of user testing of preview version

**Comment by j4mesholland** [comment]
Not stale - will be part of user testing of preview version

**Comment by CelineBoudier** [comment]
still not stale

**Comment by j4mesholland** [comment]
Not stale

**Comment by j4mesholland** [comment]
We still don't have scoring setup

**Comment by mrniket** [comment]
This has been done, closing.
