### ISSUE TITLE
Test cheat sheet code on AI:MMO

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#497]
Someone needs to test that all the code works in the game.

See cheat sheet here: [https://app.zenhub.com/files/39072690/ae37ab8d-c8d4-4d3d-ad23-83bf861211be/download](https://app.zenhub.com/files/39072690/ae37ab8d-c8d4-4d3d-ad23-83bf861211be/download)

Then delete all the functions that don't work from the sheet and code.

**Comment by j4mesholland** [comment]
Olaf wanted us to test these ourselves to confirm Andreia's notes: 
[KS3-Cheat-Sheet_AndreiaComments.pdf](https://github.com/ocadotechnology/aimmo/files/1818976/KS3-Cheat-Sheet_AndreiaComments.pdf)

**Comment by j4mesholland** [comment]
Here is the updated PDF which needs checking.
[KS3-Cheat-Sheet_Andreias_changes_to_check.pdf](https://github.com/ocadotechnology/aimmo/files/1819000/KS3-Cheat-Sheet_Andreias_changes_to_check.pdf)

**Comment by CelineBoudier** [comment]
- The document displays "avatar_state, world_state" as parameters for handle_turn but in the main games it's currently set up to world_view, events
- in general, we miss all the other things we can import such as:
    - simulation.action
    - simulation.direction
...

**Comment by CelineBoudier** [comment]
So we'd need to add:
 -  What are the possible actions the user can return at each turn? => MoveAction , WaitAction, AttackAction
-  The directions: NORTH, SOUTH, EAST, WEST and the bundled directions in ALL_DIRECTIONS

Else I think we have what is here right? https://github.com/ocadotechnology/aimmo/tree/master/aimmo-game-worker/simulation

**Comment by CelineBoudier** [comment]
Which ones? :)
Methods can return anything really.
For instance if handle_turn returns a MoveAction, that's, well, a MoveAction. That's the type of the object.
ALL_DIRECTIONS is a tuple (ALL_DIRECTIONS = (NORTH, EAST, SOUTH, WEST))
NORTH is a Direction. Direction being a class defined in the same file

**Comment by CelineBoudier** [comment]
MoveAction , WaitAction, AttackAction inherit from the parent class Action
It looks like they can be serialised into dictionaries:

def serialise(self):
        return {
            'action_type': 'move',
            'options': {
                'direction': self.direction.serialise()
            },
        }

**Comment by mariaFernando** [comment]
Not those, the ones that return score locations, etc - each location is a tuple but the functions return lists, I think 🤔

**Comment by CelineBoudier** [comment]
What are the names of the functions? Can you copy paste the thingies? :) Thanks

**Comment by mariaFernando** [comment]
<img width="951" alt="screen shot 2018-03-16 at 15 03 25" src="https://user-images.githubusercontent.com/30693435/37527963-3bd2964a-292b-11e8-9222-e52a955843a5.png">

**Comment by CelineBoudier** [comment]
aahhhh ok

**Comment by CelineBoudier** [comment]
all_cells returns "self.cells.values()" - which is indeed a list
score_cells and pickup_cells return lists you're right (tuples use () and lists [])

**Comment by CelineBoudier** [comment]
potential_spawn_locations() is nowhere to be found in the code btw as Andreia suggested.
The world_state functions:

   all_cells(self): returns a list

    score_cells(self): returns a list

    pickup_cells(self): returns a list

    partially_fogged_cells(self): returns a list

    is_visible(self, location): returns a boolean

    get_cell(self, location): returns a Cell()

    can_move_to(self, target_location): returns a boolean

**Comment by CelineBoudier** [comment]
wait which ones are we using https://github.com/ocadotechnology/aimmo/blob/master/aimmo-game/simulation or https://github.com/ocadotechnology/aimmo/tree/master/aimmo-game-worker/simulation ?
Let me have a look

**Comment by CelineBoudier** [comment]
looks like it's https://github.com/ocadotechnology/aimmo/tree/master/aimmo-game-worker/simulation

**Comment by mrniket** [comment]
I'm going to add the Development tag to this, it seems like the code isn't working so we need a developer to fix the code

**Comment by j4mesholland** [comment]
The changes have been made to the document:
[https://app.zenhub.com/files/39072690/590ab562-50fc-4894-81ae-21ed5ce7ecaf/download]
