### ISSUE TITLE
Create Compass

### ISSUE THREAD

**Issue by mariaFernando** [ocadotechnology/aimmo#504]

**Comment by mariaFernando** [comment]
![compass1.jpg](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/570db939-4bd2-40c0-addc-42d088938acc)

**Comment by OlafSzmidt** [comment]
Reviewed on slack, I like `compass2.jpg` the most.

**Comment by CelineBoudier** [comment]
As discussed on Slack, an "isometric" / mapped to the floor view might be more readable

**Comment by mariaFernando** [comment]
![compass2](https://user-images.githubusercontent.com/30693435/37350645-3c54b2da-26d1-11e8-87db-31c09f7e366a.png)

**Comment by CelineBoudier** [comment]
I really like the latest one - just concerned with the contrast white / orange

**Comment by CelineBoudier** [comment]
cc @j4mesholland @mrniket @OlafSzmidt

**Comment by mariaFernando** [comment]
![e](https://user-images.githubusercontent.com/30693435/37354295-37a71036-26d9-11e8-8509-43c6436a7882.jpg)
Putting this here to see if the contrast would be a big problem

**Comment by CelineBoudier** [comment]
that looks ok to me - we can review later if we receive feedback?

**Comment by mariaFernando** [comment]
Sounds good
