### ISSUE TITLE
Finalise the user guide for AI:MMO

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#511]

**Comment by j4mesholland** [comment]
We need to check that the functions work for this example code:[https://app.zenhub.com/files/39072690/87307fff-4635-45a7-9d43-24336bfb5935/download]

**Comment by riaJha97** [comment]
All the functions in the example code have been tested and they're all working. The only bit I wanted to point out was line 11. The variable name 'closest' needs to be replaced with the variable name 'closest_score' which was defined on the line above.

**Comment by j4mesholland** [comment]
The PDF document has now been updated:
[KS3-AIMMO-User-guide.pdf](https://github.com/ocadotechnology/aimmo/files/1877172/KS3-AIMMO-User-guide.pdf)

**Comment by j4mesholland** [comment]
Made change to code on line 11. (closest_score.location.y - avatar_state.location.y). **_score** was missing from this statement.

Updated PDF attached:
[KS3-AIMMO-User-guide.pdf](https://github.com/ocadotechnology/aimmo/files/1879370/KS3-AIMMO-User-guide.pdf)

**Comment by OlafSzmidt** [comment]
Would be nice to describe what pseudocode is in the example code section.

**Comment by j4mesholland** [comment]
Code here:

class Avatar(object):
    def handle_turn(self, avatar_state, world_state):
        from simulation.action import MoveAction
        from simulation.action import WaitAction
        import simulation.direction as direction
        import random
        
        score_locations = world_state.pickup_cells()

        closest_score = score_locations[0]
        min_dist = (closest_score.location.x - avatar_state.location.x) ** 2 + (closest_score.location.y - avatar_state.location.y) ** 2
        
        for cell in score_locations:
            dist = (closest_score.location.x - avatar_state.location.x) ** 2 + (closest_score.location.y - avatar_state.location.y) ** 2
            if dist < min_dist:
                min_dist = dist
                closest_score = cell
        
        if closest_score.location.x < avatar_state.location.x:
            next = direction.WEST
        elif closest_score.location.x > avatar_state.location.x:
            next = direction.EAST
        elif closest_score.location.y < avatar_state.location.y:
            next = direction.SOUTH
        elif closest_score.location.y > avatar_state.location.y:
            next = direction.NORTH
        else:
            return WaitAction()
            
        if world_state.can_move_to(avatar_state.location + next):
            return MoveAction(next)
  return MoveAction(random.choice(direction.ALL_DIRECTIONS))

**Comment by mrniket** [comment]
Is there anything you need help with or is this issue ready to close?
