### ISSUE TITLE
Move avatar logic outside of world_map

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#532]
## Parent Epic description
Currently, we have encapsulated the logic of the game inside of world_map. It knows how to update the score locations and avatars and pickups. Splitting up this logic into classes/modules would be more in line with the single responsibility principle. An added benefit is that once this is done, we can remove the duplication of the simulation package inside of aimmo-game-worker and aimmo-game. This should simplify changes we need to make to the user-facing API.

## Task description
In this task, we move the functions containing the avatar logic out of the world_map

**Comment by j4mesholland** [comment]
@mrniket @CelineBoudier @SKDKannan  Is this issue still in progress?

**Comment by mrniket** [comment]
@j4mesholland @CelineBoudier yup, working on it now

**Comment by faucomte97** [comment]
Not stale

**Comment by j4mesholland** [comment]
@mrniket, please can you add a description to this issue

**Comment by mrniket** [comment]
@j4mesholland This task only really makes sense with the epic description, so I added that to this task's description. Hope it helps
