### ISSUE TITLE
Create score objects

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#538]

**Comment by mariaFernando** [comment]
![Screen Shot 2018-04-24 at 10.53.22.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/a27423a3-8b75-47ae-9de2-98df3803fdd1)

![Screen Shot 2018-04-24 at 10.53.26.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/866809b3-f96c-4430-9d0c-53adb10ffc4b)
