### ISSUE TITLE
New logo for aimmo

### ISSUE THREAD

**Issue by reallinfo** [ocadotechnology/aimmo#549]
Hello, I wanted to contribute to aimmo. I designed a logo for it. If you like it, I'll send you files and pr.

Also, I can design it especially if you have something you want. Please feedback.

![aimmo](https://user-images.githubusercontent.com/36298335/39339117-a553ffe0-49cf-11e8-879d-9064ce76a119.jpg)

**Comment by j4mesholland** [comment]
@reallinfo Thank you for your logo idea! We have actually just designed a logo for the game and teaching tool:

![aimmo logo](https://user-images.githubusercontent.com/18662916/39362955-50e8917c-4a20-11e8-9d23-6c8736faac12.png)

Please check back if you are interested in contributing other ideas for the game design :-)
