### ISSUE TITLE
Change the way the UI receives game updates

### ISSUE THREAD

**Issue by jishi9** [ocadotechnology/aimmo#56]
The UI currently polls the frontend server constantly for updates.

Implement a solution where the *game simulation* server pushes updates instead - e.g. using web sockets (or some other better solution that you can think of!)

Possible server-side solutions:
1. client ==> proxy (on Kubernetes) ==> game simulation (on Kubernetes)
Here we only need one public IP address for the proxy, no matter how many game simulation servers we spawn.

2. client ==> game simulation (on Kubernetes)
We need a public IP address per game simulation. We need to investigate whether this would be a problem (e.g. can't be done dynamically, or is expensive).

**Comment by mikebryant** [comment]
I've created #70 to deal with the proxy side of things
