### ISSUE TITLE
Warning about changing default value of 'RedirectView.permanent'

### ISSUE THREAD

**Issue by jishi9** [ocadotechnology/aimmo#58]
The following warning is displayed when running aimmo locally:
> $HOME/.virtualenvs/aimmo/lib/python2.7/site-packages/django_autoconfig/autoconfig.py:205: RemovedInDjango19Warning: Default value of 'RedirectView.permanent' will change from True to False in Django 1.9. Set an explicit value to silence this warning.
>   url(r'^$', RedirectView.as_view(pattern_name=index_view)),

Looking at [this github issue](https://github.com/ppiet/piosenka/issues/15) and the [referenced commit](https://github.com/ppiet/piosenka/blob/b7fd58540b28b4751544647d962e5c61cb2930fb/urls.py) which fixes this, it seems that we need to add `url(r'^$', RedirectView.as_view(pattern_name=index_view))` or similar to `aimmo/players/urls.py`.

**Comment by mikebryant** [comment]
Actually this is a bug in django-autoconfig, I'll fix it there.

**Comment by mikebryant** [comment]
Fixed in django-autoconfig 0.5.1

**Comment by jishi9** [comment]
I'm still getting the warning message. Do you not as well?

**Comment by mikebryant** [comment]
We haven't explicitly depended on the new version - any new installs will get the latest.
If you manually upgrade `django-autoconfig`, or uninstall it, you'll end up with the latest version that has the fix.

**Comment by jishi9** [comment]
Yep that fixes it :)
