### ISSUE TITLE
Update flask in ai:mmo pods to 1.x

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#584]
Flask has reached a stable major version! Upgrading would be good to do soon!

**Comment by CelineBoudier** [comment]
+1

**Comment by j4mesholland** [comment]
@mrniket is this still required?

**Comment by OlafSzmidt** [comment]
yes @j4mesholland

**Comment by OlafSzmidt** [comment]
Flask has already been updated to `1.0.2`
