### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#608]
- Zoom buttons
- Run code FAB
- Toggle button (for console on/off)
- Menu

**Comment by j4mesholland** [comment]
For context:

![MVP-Nav-spilt-Large-screen.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/9cfc9d27-3ae9-446b-9496-66fb06c0d090)

**Comment by JCobbles** [comment]
[Screen Shot 2018-08-07 at 13.02.05.png](https://images.zenhubusercontent.com/5b4351058523244e69e00910/f15be952-48f7-480e-ad63-d1bffb407d30)
