### ISSUE TITLE
Icons for design system (design only)

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#621]

**Comment by j4mesholland** [comment]
Icon list here:
 ![Icons.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/4252f1bd-4791-44a7-9792-163a67a8dbc8)

**Comment by CelineBoudier** [comment]
the clear icon doesn't look that clear (...) on the right? not symmetrical to me here
The arrows are a bit small as well
I really like all the other ones

**Comment by j4mesholland** [comment]
The arrow icons would normally be used in menus so should be smaller in that instance. But if we need to use them elsewhere we should increase the relative size.

**Comment by mrniket** [comment]
Would the save and load icons make sense for our younger audience?

**Comment by riaJha97** [comment]
I think load looks more like a download icon?

**Comment by j4mesholland** [comment]
We could try the cloud with arrows icons for download and save. I think we need to do some user testing before we commit to changing from the default Material design icons for 'Save' and 'Download' though.
