### ISSUE TITLE
Store logs in data structure at every tick

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#632]
Make sure that logs can be identified by avatar ID

**Comment by OlafSzmidt** [comment]
We're sending single avatar logs individually from the game to the correct avatar (it's lightweight and secures any sensitive data on our end if the connection is compromised).

**Comment by OlafSzmidt** [comment]
Some progress has been done on branch `send_logs` of aimmo. I made some refactoring on commit https://github.com/ocadotechnology/aimmo/commit/18949f56c4de198eeff4f9aeb7c9845f7e8d5bc4 of that branch, but can't test if it works fine until @NiallEgan finishes & merges his work in.
