### ISSUE TITLE
Buttons for game UI (design task)

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#647]
Create all button types in Sketch master file.
- [x] FAB (Floating Action Buttons)
- [x] Primary (Contained)
- [x] Secondary (Outlined)
- [x] Text (Just text)
- [x] Toggle
- [x] Icon

**Comment by j4mesholland** [comment]
Please review the buttons and FAB

![Buttons.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/4c343369-d368-48f5-be71-c1c505ae1cd1)

![FAB.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/2a637934-95fb-43dd-8e3d-0131daac60c8)

**Comment by j4mesholland** [comment]
To give some context for the buttons:

**Comment by mrniket** [comment]
👌

**Comment by CelineBoudier** [comment]
nice!!

**Comment by CelineBoudier** [comment]
sorry, nice!!!

**Comment by OlafSzmidt** [comment]
Not a big fan of the greyish bar at the top personally

**Comment by j4mesholland** [comment]
Olaf, you could at least have used several exclamation marks!
