### ISSUE TITLE
WaitAction doesn't work

### ISSUE THREAD

**Issue by NiallEgan** [ocadotechnology/aimmo#651]
An Avatar class that simply returns a WaitAction causes the avatar to walk of the map, through blocks. This would also explain some behaviours we see when there is an error in user's code or decide_action.

**Comment by OlafSzmidt** [comment]
Doubt it's the `WaitAction` object itself. Needs investigation but imo it's just the fact that we switch tabs and no longer focus on the WebGL build itself, that's why the animations go crazy?

**Comment by NiallEgan** [comment]
Actually I just was being stupid
