### ISSUE TITLE
ubuntu_setup.sh causing terminal encoding to go crazy

### ISSUE THREAD

**Issue by OlafSzmidt** [ocadotechnology/aimmo#653]
@CelineBoudier experienced some issues with the script `ubuntu_setup.sh`. After running it lots of weird characters (random, most seemed UTF-8 though) showing up in the terminal.

Perhaps screenshots would be nice and a list of already installed packages, environments etc @CelineBoudier so we can reproduce this in the future?

**Comment by CelineBoudier** [comment]
![screenshot from 2018-07-09 17-34-27](https://user-images.githubusercontent.com/8862062/42463589-7c8d7ce0-839e-11e8-8ee2-ca43c9c5fc52.png)

**Comment by OlafSzmidt** [comment]
Can't really reproduce. Shall we close @CelineBoudier @riaJha97 ?

**Comment by CelineBoudier** [comment]
if you want - i got the error everytime though.

**Comment by riaJha97** [comment]
Is it worth testing this script on another machine?

**Comment by CelineBoudier** [comment]
Can't reproduce anymore - .....
I have another issue though, will put it

**Comment by CelineBoudier** [comment]
not an issue - it is fine
