### ISSUE TITLE
Game map not loading on existing or new game

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#685]
The game map doesn't load on the live website:
![Screen Shot 2018-07-24 at 09.56.27.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/6fcaa18f-1926-4461-8ad2-44249c3a5811)

**Comment by j4mesholland** [comment]
This needs to be working so that Rebecca can continue her report

**Comment by OlafSzmidt** [comment]
Fixed but please follow the bug issue template :)
