### ISSUE TITLE
Call to world_map.can_move_to(avatar_state.location + <value>) is failing

### ISSUE THREAD

**Issue by rdcruzCFL** [ocadotechnology/aimmo#710]
**Describe the bug**
The following code crashes with the error (from the logs) shown underneath it.
![image](https://user-images.githubusercontent.com/41337133/43640600-73e29f3e-9718-11e8-9aa6-d1d774838426.png)

![image](https://user-images.githubusercontent.com/41337133/43640584-63ff24ca-9718-11e8-9917-8f4b83ac7c68.png)

**To Reproduce**
```
class Avatar(object):
    def handle_turn(self, world_map, avatar_state):
        from simulation.action import MoveAction
        import simulation.direction as direction 
        import random

        next_dir = random.choice(direction.ALL_DIRECTIONS)
        if world_map.can_move_to(avatar_state.location + next_dir): # this line
          pass  
        else:
          next_dir = direction.SOUTH

        return MoveAction(next_dir)
```
**Expected behavior**
In this test mode, I expected the avatar to move randomly but switch to south if it encountered an obstacle. The code does not run.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
Chrome
Version 68.0.3440.84 (Official Build) (64-bit)

**Additional context**

**Comment by rdcruzCFL** [comment]
Thanks for looking into this and finding a solution!

**Comment by OlafSzmidt** [comment]
We're going to keep this open until it's fixed and merged into master.

**Comment by riaJha97** [comment]
Tried this code on staging with rxjs 6 and wasn't able to reproduce this issue. There were no other errors on the console and everything looked fine. Maybe someone else could try this on staging? Otherwise, should we close this issue?
