### ISSUE TITLE
Upgrade rxjs to version 6. 

### ISSUE THREAD

**Issue by NiallEgan** [ocadotechnology/aimmo#712]
rxjs has issues with regards to encoding certain characters, which is discussed here: https://github.com/ReactiveX/rxjs/issues/2389. This results in certain characters, e.g. `+`, to not be encoded in the url. In turn, when django comes to decode the data sent to it in the POST request, it converts the `+` into a ` `.  A fix has been released in rxjs, but requires us to upgrade to rxjs v6. 

This will fix https://github.com/ocadotechnology/aimmo/issues/710.

**Comment by OlafSzmidt** [comment]
Some more info on why this is the case: 

https://stackoverflow.com/questions/11447391/ajax-why-jquery-replaces-with-a-space

TL;DR: rxJS 6 uses a different JS encoding method (ie. encodeURIComponent) than 5 (ie. encodeURI). encodeURI treats `+` characters as spaces in HTTP methods.
