### ISSUE TITLE
Worker should not participate in game if Avatar initialization fails

### ISSUE THREAD

**Issue by jishi9** [ocadotechnology/aimmo#73]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wael.aljeshi/Documents/c4l/aimmo/aimmo-game-worker/service.py", line 38, in process_turn
    action = avatar.handle_turn(avatar_state, world_map)
AttributeError: 'NoneType' object has no attribute 'handle_turn'
```

**Comment by Spycho** [comment]
Currently, if you bug an Avatar (e.g. `def __init__(self): raise Exception('test')`, Kubernetes failes to start the pod, at which point it backs off and tries again, I think infinitely. It should probably give up and kill it after one failure? 3 failures, in case its not the player's fault? Is this a thing we can do with Kubernetes, @mikebryant? Presumably we'd also need to do something to aimmo-game to stop it just trying to spawn another avatar worker. Giving the user some feedback would be useful, which possibly means we should give up after 1 failure to avoid confusing matters?

**Comment by OlafSzmidt** [comment]
If not possible, we could add some logic to see if the avatar is properly initialized before handling the turn - but that's a very short term solution imho. 

Kubernates seems have this feature added very recently. Am I right @mikebryant? It's not to be mistaken with `restartPolicy` which is described [here](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#running-an-example-job).

The [failure policy for jobs was added just 25 days ago, if this is any relevant to this issue](https://github.com/kubernetes/features/issues/298)

**Comment by OlafSzmidt** [comment]
@mikebryant @Spycho https://github.com/OlafSzmidt/aimmo/commit/472b7a935d7dff0f5a2637edf3af30beb1a8cc55? Not sure if relevant.

**Comment by OlafSzmidt** [comment]
Still relevant.

**Comment by CelineBoudier** [comment]
Still relevant? @OlafSzmidt @mrniket

**Comment by j4mesholland** [comment]
not stale

**Comment by OlafSzmidt** [comment]
Is this applicable anymore? We removed worker recreation. What happens when the initial initialisation fails?

@NiallEgan

**Comment by NiallEgan** [comment]
If there is a problem creating the avatar (i.e. if there is an issue with the source code), this error is caught and returned to the front end. I think that this can be closed.

**Comment by NiallEgan** [comment]
Closing this as it has been dealt with in other issues.
