### ISSUE TITLE
Investigate Rebecca's issue

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#735]
@rdcruzCFL reported that the following code did not work when she tried it on production:

```
class Avatar(object):
    def handle_turn(self, world_map, avatar_state):
        from simulation.action import MoveAction
        import simulation.direction as direction
        import random

        target_x = 0
        target_y = 0
        
        # Just deal with one dimension at a time 
        # This is not very efficient but it approximates a solution
        if target_x < avatar_state.location.x:
          next_dir = direction.EAST
        elif target_x > avatar_state.location.x:
          next_dir = direction.WEST
        elif target_y < avatar_state.location.y:
          next_dir = direction.NORTH
        else:
          next_dir = direction.SOUTH
          
        return MoveAction(next_dir)
```
We should look into this, identify the fault and a potential solution.

**Comment by NiallEgan** [comment]
I have tried to replicate this on my machine, and the code works fine. This suggests that either:
a) We have a problem when lots of games are being run (at the time the bug was reported, I believe, there were 12 or so games running)
b) We have fixed it on master since the bug was initially reported

**Comment by riaJha97** [comment]
Ran this on staging and it works fine there as well.

**Comment by riaJha97** [comment]
We could test this on production or staging?
