### ISSUE TITLE
I can see unintended games

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#744]
**Describe the bug**
I was able to play a game not intended for me by accessing the game url directly 

**To Reproduce**
1. Make sure you are authorised on AI:MMO and log in
2. Go to https://www.codeforlife.education/aimmo/
3. Get the url for an existing game that is NOT in your "open play games" list
4. Access this url directly
5. You can see the game and your avatar

**Expected behavior**
You should not be able to watch or play a game not intended for your school

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - chrome

**Comment by riaJha97** [comment]
It didn't apply the migration on staging :(
