### ISSUE TITLE
Create a Worker class to remove the worker logic from TurnManager and AvatarWrapper

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#756]
## Acceptance Criteria
- [ ] Create a new class named `Worker`
- [ ] Move `fetch_data` from `AvatarWrapper` into `Worker`
- [ ] Make `GameRunner` responsible for registering worker metadata
- [ ] Rename `TurnManager` to `SimulationRunner`
- [ ] Docs
- [ ] Remove the class `FakeGameRunner`

## Analytics Requirements
N/A

**Comment by NiallEgan** [comment]
Has been made part of https://github.com/ocadotechnology/aimmo/issues/767
