### ISSUE TITLE
Move worker creation logic (local/kubernetes modes) from the WorkerManagers to the Worker

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#757]
## Acceptance Criteria
- [ ] Move worker creation logic (local/kubernetes modes) from the WorkerManagers to the Worker
- [ ] There should be only one `WorkerManager` class
- [ ] There should be `LocalWorker` and `KubernetesWorker` subclasses
- [ ] Docs

## Analytics Requirements
N/A

**Comment by faucomte97** [comment]
Not stale
