### ISSUE TITLE
Rename the ids in the game container to player_id

### ISSUE THREAD

**Issue by NiallEgan** [ocadotechnology/aimmo#769]
## Task Description
Currently, there are three different names for the same id in the game container (`player_id`, `avatar_id`, `user_id`). We should rename all of these to `player_id`.

## Acceptance Criteria
- [ ] We only have one name: `player_id`

**Comment by faucomte97** [comment]
Is this still relevant @dent50cent ?

**Comment by faucomte97** [comment]
Still relevant?

**Comment by mrniket** [comment]
Yes, still relevant

**Comment by dionizh** [comment]
De-prioritised.
