### ISSUE TITLE
Need terms and conditions that allow us to copy and execute user submitted code

### ISSUE THREAD

**Issue by mikebryant** [ocadotechnology/aimmo#77]

**Comment by CelineBoudier** [comment]
Some loosely connected EULAs / conditions:
Minecraft mods https://account.mojang.com/documents/minecraft_eula
https://www.tynker.com/terms

**Comment by CelineBoudier** [comment]
Relevant - To look into next sprint @j4mesholland ??

**Comment by j4mesholland** [comment]
Add to sprint 62

**Comment by j4mesholland** [comment]
Add to sprint 66

**Comment by j4mesholland** [comment]
@CelineBoudier  has anyone asked legal about this yet?

**Comment by j4mesholland** [comment]
not stale
