### ISSUE TITLE
Catch invalid objects returned from handle_turn earlier 

### ISSUE THREAD

**Issue by NiallEgan** [ocadotechnology/aimmo#771]
## Task Description
Currently, if the user's code returns say `None` or indeed any object which does not have a `serialise` method, the user will get a confusing error printed in the log complaining about the lack of a `serialise` method. I think we should check for this earlier and throw a custom exception with a more helpful error message. This better separates errors on our end from errors in the user's code. 

## Acceptance Criteria
- [x] A custom error message that is easy to understand is thrown if the user's `handle_turn` method does not return a valid action. 

## Analytics Requirements
N / A

**Comment by j4mesholland** [comment]
Waiting on Olaf to complete review

**Comment by j4mesholland** [comment]
Thanks @OlafSzmidt
