### ISSUE TITLE
Create a dashboard to monitor Kubernetes performance

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#776]
## Description
**We need a dashboard to monitor performance with many users using AI:MMO.**

## Acceptance criteria
- [x] Use Google cloud to do this
- [x] Decide on the data we want to monitor

**Comment by riaJha97** [comment]
I've added another dashboard for logs: Log entries/bytes per cluster/pod which you should be able to filter if you want to see the details for a specific cluster/pod.

I was looking into a chart for DB connections but unfortunately we only have one db instance so I haven't been able to show the number of connections (between dev, staging, and production) separately.

We might want to discuss any other data that we want to monitor

**Comment by mrniket** [comment]
Yeah seems like we can't monitor other stuff and make the metrics we want to make without using something like Prometheus. Dashboards look okay :)

Maybe we can improve the names of some of the dashboards and delete the test ones?
