### ISSUE TITLE
Avatar walks through obstacles

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#777]
**Describe the bug**
An avatar is able to walk through obstacles, rather than avoiding them

**To Reproduce**
Steps to reproduce the behaviour:
1. Create or load an AI:MMO game 
2. Give your avatar some instructions, these are the instructions I gave mine (so see if you can replicate with this code): 
'''class Avatar(object):
    def handle_turn(self, world_state, avatar_state):
        from simulation.action import MoveAction
        import simulation.direction as direction
        import random
        
        new_dir = random.choice(direction.ALL_DIRECTIONS)
        # Check the avatar can move this way
        next_cell = avatar_state.location + new_dir
        if world_state.can_move_to(next_cell):
          next_dir = new_dir
        else:
          # Turn around
          print("Ouch! Obstacle at", next_cell)
          if new_dir == direction.NORTH:
            next_dir = direction.SOUTH
          elif new_dir == direction.SOUTH:
            next_dir = direction.NORTH
          elif new_dir == direction.EAST:
            next_dir = direction.WEST
          else:
            next_dir = direction.EAST
        return MoveAction(next_dir)'''

**Expected behavior**
An avatar should avoid obstacles, not walk through them

**Screenshots**
![screen shot 2018-08-30 at 14 52 14](https://user-images.githubusercontent.com/18662916/44914297-ba8e0700-ad27-11e8-9b05-2bf46d5d1469.png)

**Desktop (please complete the following information):**
 - OS: [Mac OSX High Sierra]
 - Browser [Chrome]
 - Version [Version 67.0.3396.99 (Official Build) (64-bit)]

**Additional context**
None

**Comment by OlafSzmidt** [comment]
What game did this happen on, what server, was it local?

What time?

**Comment by riaJha97** [comment]
I've tried this on staging, where James had the issue. I wasn't able to reproduce it.

**Comment by faucomte97** [comment]
Haven't been able to reproduce this issue either. Tried it on staging. The avatar chooses random directions appropriately and correctly prints 'Ouch!' whenever the chosen direction would make it walk through the obstacle.

**Comment by CelineBoudier** [comment]
I've seen it happen on James' laptop. Can see if I can reproduce here

**Comment by CelineBoudier** [comment]
no i can't :/

**Comment by riaJha97** [comment]
Shall I close this?
