### ISSUE TITLE
Remove non-user code traceback (related issue: https://github.com/ocadotechnology/aimmo/issues/771)

### ISSUE THREAD

**Issue by NiallEgan** [ocadotechnology/aimmo#780]
## Task Description
At the moment, if there is an error in the user's code, the traceback will start from our code, meaning that the first line or so refer to lines of code in our own source base. For example a syntax error:
```Traceback (most recent call last):
File "/usr/src/app/avatar_runner.py", line 43, in process_avatar_turn
self._update_avatar(src_code)
File "/usr/src/app/avatar_runner.py", line 33, in _update_avatar
self.avatar = self._get_new_avatar(src_code)
File "/usr/src/app/avatar_runner.py", line 25, in _get_new_avatar
exec src_code in module.__dict__
File "<string>", line 6
print('map'f)
^
SyntaxError: invalid syntax
```

We really only want the traceback to start from line 6 in "<string>".

There are also runtime errors:
```Traceback (most recent call last):
File "/usr/src/app/avatar_runner.py", line 45, in process_avatar_turn
action = self.avatar.handle_turn(world_map, avatar_state)
File "<string>", line 6, in handle_turn
TypeError: cannot concatenate 'str' and 'int' objects
```

Again, we want the traceback to start in the user code. 

We should drop these lines off of the traceback in the worker pod to avoid this. There are two possible solutions:
a) Parse the output string which gets printed for the traceback and remove the appropriate lines.
b) Manipulate the actual exception  / traceback object in the worker to remove appropriate lines.

I think that b is preferable as parsing the string is likely to be quite fragile. 

## Acceptance Criteria
- [ ] When an runtime exception occurs, the traceback should start at a point in the user's code. 
- [ ] When a syntax error occurs, the traceback should start at a point in the user's code. ****

## Analytics Requirements
N/A

**Comment by faucomte97** [comment]
Is this still relevant @dent50cent ?

**Comment by faucomte97** [comment]
Not sure if this is still relevant, @dent50cent ?

**Comment by mrniket** [comment]
Closing this issue as it's tracked by another (see pr #988)
