### ISSUE TITLE
Warn users that they are logged out

### ISSUE THREAD

**Issue by NiallEgan** [ocadotechnology/aimmo#785]
**What is the problem that you wish to solve? Please describe.**
If the page has been open for a long time, the authentication cookie will be expired and the user will be unable to post new code. There is no way however for the user to realise this. 

**Describe the solution you'd like**
Alert the user if they are logged out so they are aware of the problem.

**Comment by faucomte97** [comment]
Still relevant, might want to discuss with @j4mesholland

**Comment by faucomte97** [comment]
Will be fixed as soon as #856 is merged in.

**Comment by mrniket** [comment]
Since the homepage of AI:MMO is on portal now, this is no longer an issue, closing.
