### ISSUE TITLE
remove irrelevant autocompletions

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#803]
<b>Describe the bug</b>
when typing certain text into the editor it may sometimes give irrelevant or unnecessary autocompletions.

<b>To reproduce</b>
1. Go to aimmo game page
2. type the number 1 anywhere on the editor
3. it will show an autocomplete suggestion as in the screenshot below.

<b>Expected behaviour</b>
Should not show autocomplete suggestions that are unnecessary, or unwanted.

<b>Screenshot</b>
![Screen Shot 2018-09-10 at 11.22.39.png](https://images.zenhubusercontent.com/5b8f9b976cb9d0508bb5f54d/3aed6caf-a865-4f91-b395-e229ca11fa7d)

<b>Additional information</b>
I've looked into this and found a possible way to solve this: There should be a way to add the language_tools extension to the ace editor, this is needed to work with completers. However there is no functionality for removing completers from the default set, so we need to come up with a way of doing this ourselves.
Here is the source code for the language_tools extension: https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/language_tools.js
The relevant code is lines 92-105.

**Comment by faucomte97** [comment]
Still relevant

**Comment by j4mesholland** [comment]
not stale

**Comment by mrniket** [comment]
it might be worth just disabling all autocompletions? Less confusing stuff for the students

**Comment by dionizh** [comment]
Autocomplete has been disabled.
