### ISSUE TITLE
The user's code may not always have an Avatar class

### ISSUE THREAD

**Issue by riaJha97** [ocadotechnology/aimmo#807]
If the user completely rewrites their code and removes the Avatar class, this will break AvatarRunner as _get_new_avatar() tries to access module.Avatar().

We need to discuss what should happen in such cases, as currently, it keeps raising an error almost every 2 seconds. The traceback printing on the console is also making references to our code.

<b> To Reproduce </b>
1. Remove all code from the editor
2. Add a very simple print statement
3. Look at the console

**Comment by faucomte97** [comment]
Not stale nor fixed

**Comment by mrniket** [comment]
Still relevant: ![image.png](https://images.zenhubusercontent.com/57616341bf93871ccd9ca73c/3c4816b9-955f-4660-9978-af76ee78e5ab)

There is no useful error message to say that they need an Avatar class (it just prints the statement once and doesn't execute future turns)

**Comment by mrniket** [comment]
The solution here could be a few things:

1. Remove the ability to remove the required code in the first place
2. Add the ability to reset the code to the default code. This would mean we would also need a useful error message when things go wrong
