### ISSUE TITLE
Investigate an automated AI:MMO setup script

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#817]
### Description 
It would be nice to have a script that someone could run after cloning the aimmo repo, `./setup-aimmo` for example, that would set up & potentially install the dependencies needed to run aimmo for whoever needs it. This would not replace the manual setup instructions on the readme on github. So all the person who ran the script should then need to do is then get the aimmo-unity package and put it in the right place.

#### Minimum requirements
- [x] Investigate if it can be cross-platform, or different scripts for each OS (mac, linux/ubuntu, windows).

#### Further requirements
- [x] The script also fetches the packages needed in order for aimmo to run (parcel, yarn, docker etc.).
- [ ] The script gets the latest aimmo-unity package so the user doesn't need to. 

### Additional notes
The script needs to inform the person using it what it's doing. If the script fails it should also inform the user. In an ideal situation we would need only to run this script whenever someone needs to setup the project

**Comment by dent50cent** [comment]
This should be possible, we'd need to write a python script using the `platform` and subprocess` modules, this would allow us to detect what operating system the script is being run on and execute shell commands based on that. Then all that would be needed is error handling to communicate with the user when and why things go wrong so they can potentially fix them.

**Comment by dent50cent** [comment]
As for getting the unity package, it may be possible to download one from the website using selenium or other method to navigate the page and click the download link. However i'm not sure how reliable this would be if for example we were to release a new version unity for aimmo.

**Comment by OlafSzmidt** [comment]
It takes an div id change on the unity website for selenium to be lost. I would reconsider if there are more important things to spend time on? :confused:

**Comment by dent50cent** [comment]
That's why I'm not focusing on implementing that. Also, it's our GitHub repo, not the unity website if that helps.

**Comment by OlafSzmidt** [comment]
It's been done, check the appengine project for our deploying scripts. We pull the latest one from an array using one of the github API's
