### ISSUE TITLE
Look into circular dependency problems within the projects.

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#831]
## Task Description
create a document to describe the current circular dependency problem within our projects and explain the solutions we've come up with in an attempt to fix them.

**Comment by faucomte97** [comment]
Not stale

**Comment by mrniket** [comment]
Semantic versioning of our projects might help with this.

**Comment by mrniket** [comment]
Semantic versioning implemented, will close this issue and open up future ones when we have decided a course of action.
