### ISSUE TITLE
Number of players in a Game too limited

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#838]
**Describe the bug**
More than 6 (>) players in a game, it freezes

**To Reproduce**
Steps to reproduce the behaviour:
1. Have more than 6 people work on the same game
2. Ask one to update code
3. It doesn't update :(
4. After this point, can't even join the game

**Expected behaviour**
Game to be available to more than 30 users

**Desktop (please complete the following information):**
 - everywhere

**Additional context**
noticed at pycon uk and reproduced in the office

**Comment by j4mesholland** [comment]
Replication of epic
