### ISSUE TITLE
Optimise games to handle a class of users

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#842]
## Task Description
When conducting user testing it was found that the any AI:MMO game with more than 5 users freezes for a time, before getting progressively worse each turn. Eventually, the game completely freezes or crashes. If the user closes the game and tries to play the same game again, the game map will not load at all.

## Acceptance Criteria
- [x] Any game can be played with more than four players and up to 30 players without freezing or crashing
- [x] The game turns should not slow down with each turn

## Analytics Requirements
Test on dev/staging with at least 20 players

**Comment by faucomte97** [comment]
Not stale
