### ISSUE TITLE
run.py -k command doesn't run minikube start

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#843]
**Describe the bug**
In the docs it is explained that running the `run.py -k` command automatically runs `minikube start`. However this is not the case. The user has to run the minikube command manually before running `run.py -k`.

**To Reproduce**
1. Make sure minikube isn't already running (if it is, run `minikube stop`).
2. Run `run.py -k`.
3. Minikube is never started.

**Expected behavior**
After running `run.py -k`, the print statements of the `minikube start` command should be visible in the command line, ie `Starting VM...` etc.

**Screenshots**
N/A

**Desktop**
Everywhere.

**Additional context**
N/A

**Comment by OlafSzmidt** [comment]
The `minikube.py` file in `aimmo_runner` is supposed to be responsible for this. The `-k` should eventually make a call to `start()` in `minikube.py`. I'd start looking around there for the problem ;[

**Comment by faucomte97** [comment]
Yup :) We had a look there and Paris managed to fix the issue. PR coming soon :stuck_out_tongue: 
Thanks!
