### ISSUE TITLE
Prototypes for new AI:MMO game page

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#853]

**Comment by j4mesholland** [comment]
Please review: https://sketch.cloud/s/1xxbp/WkVyjk/play

**Comment by faucomte97** [comment]
Looks good :) Are you sticking with the 'back' link under the game creator box or did you want to replace it with a bigger 'Cancel' link instead?

**Comment by j4mesholland** [comment]
@faucomte97 I went with a larger Cancel link. Please see updated prototype here: https://sketch.cloud/s/1xzny/O3zZ5w/play

**Comment by OlafSzmidt** [comment]
Not a big fan of the dropdown menu before the "Create a new game" button. Doesn't look intuitive, at first I thought create a new game was a 'confirm selection' type of button for the dropdown.

Apart from that it's good!

**Comment by j4mesholland** [comment]
Hi Olaf!

If the user clicks one of the links on the drop-down menu they will be taken to the game, so that shouldn't be an issue. I think we should review with users to see if they have any confusion, then redesign if necessary. I will update the prototype for clarity.

**Comment by j4mesholland** [comment]
@rdcruzCFL tested the prototype and wasn't confused. Lets test with more users once live.
