### ISSUE TITLE
Monitor the cluster

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#865]
## Task Description
We should now have a prometheus deployment ready to monitor the cluster, it will not be monitoring anything at this time however. In order to set up prometheus to monitor the cluster we can use a number of config maps, There are alternative examples in the [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) manifests section of the [prometheus operator](https://github.com/coreos/prometheus-operator) repo.

## Acceptance Criteria
create config maps or alternative to monitor: 
- [ ] "kube-state-metrics", or state of the cluster
- [ ] "node-exporter", typically done as a daemon set

[This](https://coreos.com/blog/the-prometheus-operator.html) link provides more information on making use of the operator to monitor the cluster using these config maps. These should then be seen in the targets section of the prometheus UI, and will list the endpoints they monitor.

**Comment by CelineBoudier** [comment]
not stale
