### ISSUE TITLE
Monitor the cluster's services

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#866]
## Task Description
In addition to monitoring resource usage, nodes, and kublets. We want to monitor the services within the cluster, this is done via service monitors. (There should be a service monitor custom resource ready for you to use for this process).

[This](https://coreos.com/blog/the-prometheus-operator.html) link details an example of using service monitors

## Acceptance Criteria
- [ ] create service monitors for the cluster
- [ ] update the prometheus deployment to include the service monitors

**Comment by CelineBoudier** [comment]
not stale
