### ISSUE TITLE
Create a custom metric

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#867]
## Task Description
Implement custom metrics for AI:MMO, the most obvious and potentially most useful metric we could have is measuring the turn time from the games. It seems as though we can use the [python client](https://github.com/prometheus/client_python) to implement this, the service monitors would then pick up the new metric ready to be processed.

## Acceptance Criteria
- [ ] create custom metric to monitor game turn time.
- [ ] This section will definitely need documentation as other's in the future will need to know how this is done.

**Comment by CelineBoudier** [comment]
not stale

**Comment by mrniket** [comment]
QA'd
