### ISSUE TITLE
Create an Alert manager

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#869]
## Task Description
It would be nice to set up the alert manager (see [Grafana](https://grafana.com/) and [prometheus](https://prometheus.io/docs/introduction/overview/) documentation for details) to for example send a slack message when a game pod is taking too long to process a turn.

## Acceptance Criteria
- [ ] Create a deployment for the alert manager
- [ ] document the process of creating an alert (if needed) for members of the project to use when they want to make use of the alert manager.

**Comment by CelineBoudier** [comment]
no stale
