### ISSUE TITLE
Update AI:MMO Indentation guide

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#884]
## Description
Update indentation guide as per Rebecca's guidence to inclue an error.

## Acceptance criteria
- [ ] Check updates with Rebecca

**Comment by faucomte97** [comment]
Not stale

**Comment by j4mesholland** [comment]
I have updated to include an error example as Rebecca suggested.

@rdcruzCFL please can you review. Thanks :-)

[https://app.zenhub.com/files/39072690/c092c229-01bb-46b4-b2f2-43c6fbf9d60d/download](https://app.zenhub.com/files/39072690/c092c229-01bb-46b4-b2f2-43c6fbf9d60d/download)

**Comment by rdcruzCFL** [comment]
That is really clear, yes, thanks.
