### ISSUE TITLE
Update AI:MMO Understand the turn based game guide

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#885]
## Description
Update  as per Rebecca's guidence.

## Acceptance criteria
- [x] Check updates with Rebecca

**Comment by j4mesholland** [comment]
Rebecca's notes:

Typo in title: turn-based, not turn based
• Replace all instances of “turn based” with “turn-based”
• A question: is it possible for a student to block AI:MMO by, for example, adding an
infinite loop to their handle_turn function? If they can, they probably will!
• Change reference to world_state to world_map
• Update fig 2.1
• Update code in fig 3.1
o self. prefix is not needed when referencing avatar_state or world_map – they
are parameters, not properties
o Remove multiple return points – poor practice. Instead, set a variable in the
if…elif…else statement and return it afterwards
• Update the last bullet points to remove self. prefix

**Comment by faucomte97** [comment]
Not stale

**Comment by rdcruzCFL** [comment]
I have used the code structure from AIMMO_challenge2_jan19.pdf
```
class Avatar():
    def handle_turn(self, world_state, avatar_state):
        # Check to see if the avatar can move in each direction
        if world_state.can_move_to(avatar_state.location + direction.NORTH):
            next_dir = direction.NORTH
        elif world_state.can_move_to(avatar_state.location + direction.SOUTH):
            next_dir = direction.SOUTH
        elif world_state.can_move_to(avatar_state.location + direction.EAST):
            next_dir = direction.EAST
        else:
            next_dir = direction.WEST # Just try moving West if no other direction is available

        return MoveAction(next_dir)

```

**Comment by j4mesholland** [comment]
@rdcruzCFL I have updated the PDF with your new code snippet, thank you.

[https://app.zenhub.com/files/39072690/b3d3d33e-6b73-451f-b560-8f43568afb72/download](https://app.zenhub.com/files/39072690/b3d3d33e-6b73-451f-b560-8f43568afb72/download)

**Comment by rdcruzCFL** [comment]
That's great, thanks James.
