### ISSUE TITLE
Update AI:MMO Code Cheat Sheet

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#886]
## Description
Update cheat sheet guide as per Rebecca's guidance.

## Acceptance criteria
- [x] Check updates with Rebecca

**Comment by j4mesholland** [comment]
Rebecca's notes:

Fig 1.1 is out of date
• Rephrase “The Avatar class is where your intelligence lives.” to something like “The
Avatar class is where you put your instructions to give your character some artificial
intelligence” ?
• Rephrase “At each turn, the method1 handle_turn() is being called.” to something like,
“AI:MMO calls your handle_turn subroutine in each game turn”
• Rephrase “handle_turn() has three parameters, self, avatar_state and world_state. Please
ignore self for now, as this will be explained at a later stage.” to something like “The
handle_turn subroutine is sent information about the avatar in avatar_state and information
about the game map in world_map”
• The document refers to world_state, the object is called world_map now
world_map
• Specify the properties of a cell object
• Subroutine, can_move_to, returns a Boolean, not an integer
• Add max_x, max_y, min_x, min_y and attackable_avatar methods?
Actions
• Add a note that you must have imported direction as follows for direction.NORTH etc
to work: import simulation.direction as direction
Pickups
• It is not clear what to do with this. How do you pick these up? How do you know how
many you have etc?

**Comment by faucomte97** [comment]
Not stale? @j4mesholland ?

**Comment by j4mesholland** [comment]
@rdcruzCFL  I have updated this file. However, I have a few queries:

Fig 1.1 is out of date 
**_Done_**


• Rephrase “The Avatar class is where your intelligence lives.” to something like “The
Avatar class is where you put your instructions to give your character some artificial
intelligence” ? 
**_Done_**

• Rephrase “At each turn, the method1 handle_turn() is being called.” to something like,
“AI:MMO calls your handle_turn subroutine in each game turn”
**_Done_**


• Rephrase “handle_turn() has three parameters, self, avatar_state and world_state. Please
ignore self for now, as this will be explained at a later stage.” to something like “The
handle_turn subroutine is sent information about the avatar in avatar_state and information
about the game map in world_map” 
**_Done_**


• The document refers to world_state, the object is called world_map now
world_map 
**_We decided to keep this as world_state_**

• Specify the properties of a cell object
**_I wasn't sure where this is meant to go..._**


• Subroutine, can_move_to, returns a Boolean, not an integer
**_Done_**


• Add max_x, max_y, min_x, min_y and attackable_avatar methods?
**_I wasn't sure where this is meant to go..._**


**Actions**
• Add a note that you must have imported direction as follows for direction.NORTH etc
to work: import simulation.direction as direction
**_As we aren't showing the imports, I don't think we need this explaination_**

**Pickups**
• It is not clear what to do with this. How do you pick these up? How do you know how
many you have etc?
**_I have removed the pickups section until lit is clear how we will implement these._**

## Updated file here:

[https://app.zenhub.com/files/39072690/07683522-a905-4731-9aff-28496c76bd97/download](https://app.zenhub.com/files/39072690/07683522-a905-4731-9aff-28496c76bd97/download)

**Comment by rdcruzCFL** [comment]
• Specify the properties of a cell object
James: I wasn't sure where this is meant to go...
Rebecca: Could we have another banner similar to avatar_state methods for cell properties, perhaps with an example line of code?

• Add max_x, max_y, min_x, min_y and attackable_avatar methods?
James: I wasn't sure where this is meant to go...
Rebecca: Maybe under an Avatar heading, similar to the above? I assume attackable_avatar is just a subclass of Avatar? Does Avatar have these properties?

**Comment by j4mesholland** [comment]
@rdcruzCFL,

• Specify the properties of a cell object
James: I wasn't sure where this is meant to go...
Rebecca: Could we have another banner similar to avatar_state methods for cell properties, perhaps with an example line of code?

**I have added this**

• Add max_x, max_y, min_x, min_y and attackable_avatar methods?
James: I wasn't sure where this is meant to go...
Rebecca: Maybe under an Avatar heading, similar to the above? I assume attackable_avatar is just a subclass of Avatar? Does Avatar have these properties?

**We don't use these at the moment**

**I have added an updated PDF for approval, thanks

[https://app.zenhub.com/files/39072690/cd76d65a-83f1-470a-8681-b0217db6c055/download](https://app.zenhub.com/files/39072690/cd76d65a-83f1-470a-8681-b0217db6c055/download)

**Comment by rdcruzCFL** [comment]
That looks good to me. I suspect we will need to alter it as pupils use it but that is to be expected.
