### ISSUE TITLE
Update AI:MMO student challenge sheets

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#897]
## Description
To reflect feedback from teachers and user testing, that we want to hide the scary imports and the use of (object). Rebecca and I also discussed changing the default code from 

```
class Avatar:
	def next_turn(self, avatar_state, world_state):
		return MoveAction(random.choice(direction.ALL_DIRECTIONS))
```

To 

``` 
class Avatar:
	def next_turn(self, avatar_state, world_state):
		return MoveAction(direction.NORTH)
```

As too much time is required in a lesson to explain the imports and changing the default code from all directions to N,S,E or W.

## Acceptance criteria
**The challenges will need to be rewritten to reflect**
Challenge 1
- [ ] Removing the ```handle_turn()``` introduction
- [ ] Getting the class to move their avatar the direction to something other than ```direction.NORTH```
- [ ] Add the relevant move commands from the Cheat Sheet to this document to keep the lesson more focused (stop players from trying to attack rather than focussing on the lesson!)

Challenge 2
- [ ] Removing the ```handle_turn()``` introduction and update Fig. 1 – Default code
- [ ] Better explaination of the ```avatar_state.location``` code by adding the info from the Cheat sheet)

## Analytics
- [ ] Test with a class

**Comment by j4mesholland** [comment]
Existing challenge sheets here:

Challenge 1
[https://app.zenhub.com/files/39072690/845fbd77-4f02-44ea-9e90-b5fc696404e3/download](https://app.zenhub.com/files/39072690/845fbd77-4f02-44ea-9e90-b5fc696404e3/download)

Challenge 2
[https://app.zenhub.com/files/39072690/5c5c3e34-7376-44b9-8e84-a6ad95e77793/download](https://app.zenhub.com/files/39072690/5c5c3e34-7376-44b9-8e84-a6ad95e77793/download)

**Comment by rdcruzCFL** [comment]
[https://app.zenhub.com/files/39072690/ec3a7a72-844a-4386-9e7d-f823840ab3e2/download](https://app.zenhub.com/files/39072690/ec3a7a72-844a-4386-9e7d-f823840ab3e2/download)

I altered the text for the Challenge sheets and put them in this new document. I thought would make it easier to change them - sorry if it doesn't!
https://drive.google.com/open?id=1Xoss-yZiTY8kwACSc7a-6sSFFb-jlIxT2kBCVKBo5aM

**Comment by rdcruzCFL** [comment]
Are you waiting on me for anything here, James? I think I have done what I needed to do.

**Comment by j4mesholland** [comment]
Hi Rebecca, I’m working in this at the moment - the file you have supplied is fine, so you don’t need to do anything else at this stage.

**Comment by j4mesholland** [comment]
Please review...

**Updated Game UI Prototype here:**
https://sketch.cloud/s/Px84v/DPVpeKy/play

**PDF sheets**
Challenge 1:
[https://app.zenhub.com/files/39072690/b27cc38c-dc2d-46f7-a0cb-8b347f7c0f82/download](https://app.zenhub.com/files/39072690/b27cc38c-dc2d-46f7-a0cb-8b347f7c0f82/download)

Challenge 2:
[https://app.zenhub.com/files/39072690/53626826-3c2e-4f89-8436-27873d04bd24/download](https://app.zenhub.com/files/39072690/53626826-3c2e-4f89-8436-27873d04bd24/download)

**Comment by CelineBoudier** [comment]
I really like the UI prototype!
I'm also wondering if at some point, they'd like to have a list of the completed challenges as well, so they can "feel" / visualise the progress?

**Comment by mariaFernando** [comment]
Really like the UI prototype too! Just have a little (picky) thing to point out - the phrasing in this could be a bit misleading. "your turn" implies there are alternate turns (each player has a turn at the time?) 
<img width="255" alt="screenshot 2019-01-08 at 15 50 23" src="https://user-images.githubusercontent.com/30693435/50841915-9c7f8580-135d-11e9-8163-85c2c067ae7c.png">

**Comment by rdcruzCFL** [comment]
This looks really good, James! It is clear and easy to read and the tasks are split up into good chunks. The buttons and icons are all great and I like the side bar pop outs. 

Some suggestions:
- Icons can help to highlight key points, exercises, things to think about etc. E.g. 
![image.png](https://images.zenhubusercontent.com/5b4e282aedf0570a96a155c1/245fbaf1-47c1-4b58-8840-c16b417735b5)
A highlighted box with a suitable icon (? ! i etc.), perhaps?
- With the 'I didn't get it at all', I suspect pupils will think they can just give up at this point or be given the answer! You might like to include 'try again'
- Challenge goal: Move your avatar
    - 2/5 "Take care to use lower case and upper case *correctly*." ?
    - 3/5: "Your first challenge is to *write some code to* return a random direction"
- Challenge goal: Avoid the obstacles
    - Page 1: 2nd para, line 3: obstacle instead of obsticle
    - Page 1: 3rd para, line 1: intelligence instead of inteligence (double-l)
    - Page 3: "Now extend your code...". Highlight 'next_cell' as it is code

**Comment by CelineBoudier** [comment]
I'm reviewing the teaching materials, here are a few comments:

SC1:
- Really nice and with an appropriate level and explanations and room for improvements / creativity
- I'm a bit worried we are using different working for the same things in RR and here? Like sub routines, procedures in RR... ?
- The default code in our game is still the random one - I don't think it should right? @faucomte97 @j4mesholland @mrniket 
- "Remember to use one of the code methods
(constants) shown above."  => they are not methods. Methods are like functions/procedures/subroutines
- "You can check by writing, print(“random.randint(1,3)”), to the console log. "  -> wouldn't 1,4 make more sense ?

**Comment by CelineBoudier** [comment]
SC2:
- same question about subroutines?
- "print(“Co-ordinates of next cell”, next_cell)" in section 3 => next_cell isn't defined anywhere. I think it should be avatar_state.location+ next_move??  
- especially in section 4, there is a confustion between next_dir and next_move. It should be consistent with previous naming, and in the example for 4. it doesn't work as next_move isn't defined in the situation. To stay consistent with 3. it should be next_move but then next_dir just above needs to be renamed.

**Comment by mariaFernando** [comment]
@CelineBoudier what's the verdict on the subroutine issue, then?

**Comment by CelineBoudier** [comment]
I think it should be consistent, @mariaFernando - any thoughts @rdcruzCFL ?

**Comment by mariaFernando** [comment]
Made some of the changes to the Challenge files, not the subroutine fix (yet). Review please? :) 
SC1:
[https://app.zenhub.com/files/39072690/980b69de-62c4-4fe6-a79e-2477588e7d52/download](https://app.zenhub.com/files/39072690/980b69de-62c4-4fe6-a79e-2477588e7d52/download)
SC2:
[https://app.zenhub.com/files/39072690/e1363c26-ec3c-44f3-8da8-95921d143290/download](https://app.zenhub.com/files/39072690/e1363c26-ec3c-44f3-8da8-95921d143290/download)

**Comment by mariaFernando** [comment]
![Screenshot 2019-01-15 at 16.31.05.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/dc0cdc46-1a77-4065-b787-5072f121d506)

About this section, I reckon it would be better to have something like
"I did it" "I did it but didn't fully understand" "I couldn't do it"

![Screenshot 2019-01-15 at 16.33.44.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/4951962c-40e6-4b62-a07b-00031a97230d)

@j4mesholland @rdcruzCFL any thought on this?

**Comment by rdcruzCFL** [comment]
In the DofE's curriculum, we see:
- "design and develop modular programs that use procedures or functions"
I don't think we should make a distinction between procedures or functions but I have no particular preference for subroutine or sub-program. In some ways, sub-program is more descriptive.

**Comment by j4mesholland** [comment]
@mariaFernando for the share and review, your version is much better :-)

**Comment by mariaFernando** [comment]
Small change but what do you think about having the challenge goal and code method icons somewhere in the tabs when they open?
 ![1.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/e0428911-99ae-42cf-8b1e-e3f42922311b)
![2.png](https://images.zenhubusercontent.com/59d36f88b0222d5de47a1104/76af2a49-5929-4aed-bbba-907bfd444c48)

**Comment by mariaFernando** [comment]
Did that change on the Sketch prototype
https://sketch.cloud/s/mEqg7/ZOpaAwv/play

**Comment by j4mesholland** [comment]
Thanks @mariaFernando, that looks good. Could you add the code hints icon to the code hints tint boxes as well?

**Comment by mariaFernando** [comment]
https://sketch.cloud/s/mEqg7/25ko4eJ/play
Like this? :)

**Comment by j4mesholland** [comment]
Perfect! Thanks
