### ISSUE TITLE
Update AI:MMO -  Session 1 teacher guidance

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#898]
## Description
To reflect feedback from teachers and user testing, that we want to hide the scary imports and the use of (object). Rebecca and I also discussed changing the default code from 

```
class Avatar:
	def next_turn(self, avatar_state, world_state):
		return MoveAction(random.choice(direction.ALL_DIRECTIONS))
```

To 

``` 
class Avatar:
	def next_turn(self, avatar_state, world_state):
		return MoveAction(direction.NORTH)
```

As too much time is required in a lesson to explain the imports and changing the default code from all directions to N,S,E or W.

## Acceptance criteria
**The challenges will need to be rewritten to reflect**
#### Introduction
- [ ] No longer having to include the API docs at this stage (those instructions will be on the student challenge sheets
- [ ] Decide if we want to explain/show the turn-based game video or not
##### Recap
- [ ] update to reflect that we won't need to mention ```random.choice```
#### Challenge 1
- [ ] Update **Solution** Fig. 2 to reflect removal of imports etc.
- [ ] Update **Share and review** Fig. 3 and Fig. 4 to reflect removal of imports etc.
#### Challenge 2
- [ ] Update **Solution** Fig. 5 to reflect removal of imports etc.

## Analytics
- [ ] Test with a class

**Comment by rdcruzCFL** [comment]
Sorry, I can't find the document for this. Please will you send me a link?

**Comment by j4mesholland** [comment]
@rdcruzCFL I have sent you a link to the InDesign file if you feel you can edit that via email. Please let me know if you struggle and you can mark up a PDF, or rewrite in a Google Doc instead.

**Comment by rdcruzCFL** [comment]
I couldn't attach the file so I have uploaded it to Google Drive:
https://drive.google.com/open?id=1rXv_XbORfjgUJFDuIBF2f9zyJQdau3-F

re: *Decide if we want to explain/show the turn-based game video or not*
I left it in as I thought they could decide if they or the video could explain it better. 

Sorry, I can't work out how to move the background graphics, e.g. Student Challenge banner top of page 2, and the code background are now too large. 

Can you double-check the order of parameters to next_turn is correct please? I know there was some question about this and your instructions on this task meant my changing the order.

**Comment by j4mesholland** [comment]
Not stale. To be worked on very soon!

**Comment by j4mesholland** [comment]
I have fixed some formatting issues and updated the 'Resources' section to include:
- AI:MMO User Guide: 
   - AIMMO_User_guide.pdf
- Student handouts:
   - Intermediate_Python_SC1.pdf
   - Intermediate_Python_SC2.pdf
- Code reference cheat sheet:
   - AIMMO_cheat_sheet.pdf
-Python indentation guide:
   - Python_Indentation.pdf
- Understanding the turn–based game:
   - AIMMO_Next_Turn.pdf

I can confirm that the correct order of the next_turn parameters is 
(self, world_state, avatar_state)
I have updated the PDF accordingly.

I have removed the reference to the video, as this is not up-to-date it could be confusing to users. I have referenced the PDF document instead, which is up-to-date.

This should be good to go now:

[https://app.zenhub.com/files/39072690/410739c6-a385-4945-8b84-6c7cb0075e90/download](https://app.zenhub.com/files/39072690/410739c6-a385-4945-8b84-6c7cb0075e90/download)
