### ISSUE TITLE
Syntax Warnings in console

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/aimmo#900]
**Describe the bug**
If the player uses print() in the console and updates the code, the console will output some syntax warnings. This is because the Restricted Python automatically adds these to the logs when it compiles code. These only warn of the difference with the print() function in Python 2 vs 3, and as such aren't wanted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Wait for PR #896 to be merged in.
2. Pull.
3. Go on a game.
4. Update the avatar code with a print() statement, update the code.
5. Observe the Syntax Warnings in the console.

**Expected behaviour**
The Syntax Warnings should not appear in the console.

**Screenshots**
![syntax](https://user-images.githubusercontent.com/33633200/48770086-407d7680-ecb5-11e8-881e-8b3842f69c60.png)

**Desktop:**
All

**Additional context**
There is already a line from the logs that we are removing before it gets outputted to the console. We used a regex to match the pattern and remove it.
We tried doing the same with the syntax warnings but the regex we had for some reason did not match or remove the warnings from the logs, even though the regex seems to work on a local python console and in an online regex tester.

**Comment by faucomte97** [comment]
Still relevant

**Comment by dent50cent** [comment]
This was fixed a while ago.
