### ISSUE TITLE
Worker takes too long to get ready

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#907]
## Task Description
Since adding restricted python to the workers, they've taken a very long time to get ready before the avatar starts moving around in the games, with or without Minikube (has also been seen on the dev server). This has taken around 4 minutes in the worst case for me so far. This might frustrate users when this is released to the users when they join a new game and have to wait a few minutes before they can do anything.

## Acceptance Criteria
- [ ] Workers take far less time to get ready, ideally no more than a couple of seconds.

**Comment by j4mesholland** [comment]
@dent50cent has this issue been resolved now?

**Comment by mrniket** [comment]
We will monitor this issue, closing for now.
