### ISSUE TITLE
Set up simpler default code for AI:MMO avatars

### ISSUE THREAD

**Issue by CelineBoudier** [ocadotechnology/aimmo#918]
## Task Description

Now that we have hidden imports and understand the need to provide a simple first example,
The suggested default code is:

`class Avatar:`
    `___def next_turn(self, world_state, avatar_state):`
    `______return MoveAction(direction.NORTH)`

## Acceptance Criteria

- [x] handle_turn renamed as next_turn doesn't break anything

- [x] Rebecca approves

**Comment by CelineBoudier** [comment]
See the teaching materials.

**Comment by mrniket** [comment]
QA'd
