### ISSUE TITLE
Improvements to RunCodeButton error state

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#925]
## Description
The RunCodeButton Now has multiple states to inform the user what's going on, including an error state that shows when a timeout is detected (of the Avatar not updating). However ideally the error button should look like the one in the following example:
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3537316534313335626639333837316363643961303037382f38646535346666392d633433612d346563652d613766612d333232303530383536386538.jpeg](https://images.zenhubusercontent.com/5b8f9b976cb9d0508bb5f54d/a761ec6e-4913-45ef-9829-5b3274e11581)

## Criteria 
- [x] Button is the dark version of the purple in our theme
- [ ] Snackbar type message appears to give more details to the user

**Comment by mrniket** [comment]
@j4mesholland I think the current version of the run code button is the correct color right? Just wanted to confirm
