### ISSUE TITLE
Updating user's code takes a long time

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#928]
## Task Description
When you click the run code button in any aimmo game, it can take quite a long time before your code is actually updated in the server. However an interesting thing to note is if you run a game locally, changed the code and click the button, then close the server before it seems to finish, then as the server closes it will send back a response saying it has updated successfully.

Reopening the same game after restarting the server shows that it did, in fact, manage to update the code before closing. This could mean there is something slowing down the code update process within the workers that w can improve to get it running faster.

## Acceptance Criteria
- [ ] Identify what's causing the code update to take so long.
- [ ] Fix what's causing the problem.

**Comment by mrniket** [comment]
We should track this in our analytics/metrics so we can decide if the updating time is beyond our threshold.
