### ISSUE TITLE
Game creator doesn't change on deploy?

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#971]
**Describe the bug**
So I found this when I was implementing custom metrics. I was trying to make a change to the game manager so it would give the service ports for the games a name by adding: `name='tcp'` to the line `ports=[kubernetes.client.V1ServicePort(protocol='TCP', port=80, target_port=5000)]`. However once this was deployed to the dev cluster the services still had no name, upon inspection of the code inside of the game creator I found that my changes did not appear despite it having the correct version number.

**To Reproduce**
1. Make a change to the game creator
2. Deploy to dev
3. open a terminal in the game creator pod
4. view the file with the code you changed to inspect if the chance occurred.

**Expected behavior**
Change should be there.

**Comment by mrniket** [comment]
Looked into this, looks like aimmo-game-creator probably isn't using the versioned tag so this is an issue on staging and production as well

**Comment by mrniket** [comment]
Fixed in another PR, it was solved by setting the imagePullPolicy to Always
