### ISSUE TITLE
Look into reducing CPU Requests were we can

### ISSUE THREAD

**Issue by mrniket** [ocadotechnology/aimmo#978]

**Comment by dent50cent** [comment]
After some investigating, it seems we can make improvements to the following areas:

#### default

* When idle, games consume ~0.0020 CPU, this value seems to increase by ~0.003 per worker. Thus for 30 workers that's an additional 0.090 CPU, giving a total of **0.0110** as our request for CPU.

* Worker CPU cannot be reduced further, while they are currently somewhat underutilized, this will change in the future as user's code becomes increasingly more complex while they solve levels and challenges (However memory can probably be halved).

* The Game creator currently has no requests or limits. However, it's CPU usage at the time of writing was 0.004 on both staging and default, I am unsure of how this changes with the number of games. For now, **0.004** is a reasonable CPU request.

#### monitoring

* The requests on the monitoring setup currently highly over-estimate the CPU usage for Prometheus and Grafana. We can reduce the CPU requests of pods for the namespace down to **10%** of their current values, except for the `prometheus-k8s` and `operator` pods which can be reduced down to **40%** of their current values.

#### kube-system

* kube-system is another bring drain on how much CPU we can make use of. We can comfortably reduce the requests of everything in this namespace down to **20%** of their current values. However, it is very likely that as the number of pods and other resources increase, so to will the requirements of things within kube-system so we will need to keep an eye on this.

---

That covers every single pod on our cluster. I would recommend pod limits of x1.5-x3 the amount of the pod requests.

*Note: suggestions for CPU requests are highlighted in **bold***
