### ISSUE TITLE
Set up Cluster Autoscaling 

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#984]
## Description

It is possible for us to autoscale the number of nodes we have available to us. This generally adds nodes if pods are seen as pending, that is there are not enough resources on the current nodes for them. Nodes are removed if they are sufficiently underutilized for a certain period of time. Node minimum and maximum number of nodes can be set.

[This](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-autoscaler) link shows how to implement cluster autoscalers on GCE.

**Comment by mrniket** [comment]
Waiting for authorization

**Comment by mrniket** [comment]
Decided not to do this right now, we will focus on other optimizations instead
