### ISSUE TITLE
Set up Vertical pod autoscalers

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#985]
# Description

We can scale up our pods using vertical pod autoscalers. This allows pods to adjust the resource limits if they have too much, or not enough CPU/memory. However, in order for this to work a pod will restart whenever its limits are adjusted which would cause significant problems for our pods Considering so much of our data is not persisted across restarts within the games and workers.

[This](https://medium.com/magalix/kubernetes-autoscaling-101-cluster-autoscaler-horizontal-pod-autoscaler-and-vertical-pod-2a441d9ad231) article contains information on this type of scaling and its limitations. [Here](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) is a link to the github page for vertical autoscalers with setup information.

**Comment by faucomte97** [comment]
We've decided not to work on this at this time.
