### ISSUE TITLE
Set up horizontal pod autoscalers

### ISSUE THREAD

**Issue by dent50cent** [ocadotechnology/aimmo#986]
# Description

One way we can tell our cluster to scale is through horizontal pod autoscalers. These adjust the number of replicas that a deployment or replica set has based on one or more specified conditions. This kind of scaling works best for stateless applications or applications where the uniqueness of a pod doesn't matter too much. 

As a result, we may need to rethink the infrastructure of our game in order to get the most use out of this method.

[This](https://medium.com/magalix/kubernetes-autoscaling-101-cluster-autoscaler-horizontal-pod-autoscaler-and-vertical-pod-2a441d9ad231) contains information on how this type of scaling works. Also, [Here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/) is an example of how to set up vertical autoscaling.

**Comment by faucomte97** [comment]
We've decided not to work on this at this time.
