### ISSUE TITLE
Games deleted on Django admin not being deleted on Kubernetes

### ISSUE THREAD

**Issue by j4mesholland** [ocadotechnology/aimmo#995]
**Describe the bug**
Some games have been deleted on Django admin, however, this is not reflected on Kubernetes, with the pods still continuing to run. Django lists 13 games, Grafana lists 16 games and Google Cloud Platform lists 16 games.

**To Reproduce**
1. Go to your Django admin account and check the number of games running
2. Go to Grafana dashboard and check the number of games running
3. Go to Google Cloud Platform https://console.cloud.google.com/kubernetes/discovery?organizationId=904145293008&project=decent-digit-629
4. See if you can see a discrepancy in the number of games

**Expected behaviour**
I would expect that the games are removed from Kubernetes, once they have been deleted from the Django administration

**Screenshots**
Django admin listing 13 games
![Screen Shot 2019-02-22 at 14.32.27.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/5d53db41-c264-42f9-9be0-96821333e609)

Portal confirms that game doesn't exist
![Screen Shot 2019-02-22 at 14.33.23.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/5d3a139c-269f-483e-97b8-1a348b74c249)

But Google Cloud Platform shows 16 games running:
![Screen Shot 2019-02-22 at 14.32.03.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/6c93ae4b-e7c2-4bc1-b7bc-55b8485c2a5b)

As does Grafana:
![Screen Shot 2019-02-22 at 14.48.00.png](https://images.zenhubusercontent.com/571e4135bf93871ccd9a0078/c624ca50-608e-4596-9998-6e5bba3dd2e2)

I deleted game 98 to check this.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by faucomte97** [comment]
Can't work on it at the moment since minikube is broken and Docker is down

**Comment by j4mesholland** [comment]
Are there still issues with Docker and Minikube?

**Comment by faucomte97** [comment]
Haven't been able to get minikube to fix since, Docker is working fine though. I've shown this issue to @dent50cent and it seems like the games never actually get deleted after we delete them from Django, they only get deleted properly once we deploy to staging, which recreates the game-creator. @dent50cent seemed to think that we're just missing functionality to delete the games properly.
